// Generated by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
	id: "soia-dsh-client-ui-live-tasks",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
let _deepseek_ai_dsh_client_ui_primitives = require("@deepseek-ai/dsh-client-ui-primitives");
let react_jsx_runtime = require("react/jsx-runtime");
let react = require("react");
//#region src/shared/live-task-state.ts
/** One frozen array reused for every state without open tool calls. */
const NO_EVENTS = Object.freeze([]);
const NO_ACTIONS = Object.freeze([]);
const NO_TIMELINE = Object.freeze([]);
const NO_TURNS = Object.freeze([]);
const NO_SPANS = Object.freeze([]);
/** Usage before any message reported it. */
const INITIAL_USAGE = Object.freeze({
	reported: 0,
	input: 0,
	output: 0,
	cacheRead: 0,
	reasoning: 0,
	total: 0
});
/** Counters start at zero; nothing has been folded yet. */
const INITIAL_HEALTH = Object.freeze({
	folded: 0,
	ignored: 0,
	unknown: 0,
	frames: 0,
	deltasAccepted: 0,
	deltasDropped: 0,
	agents: 0,
	registry: 0
});
/** One frozen array reused for every state without open tool calls. */
const NO_TOOLS = Object.freeze([]);
Object.freeze({
	turn: null,
	step: null,
	running: false,
	seq: 0,
	updatedAt: null,
	lastTool: null,
	openTools: NO_TOOLS,
	toolCallsInTurn: 0,
	toolCallsTotal: 0,
	failuresTotal: 0,
	toolsAvailable: null,
	streamedTextLength: 0,
	streamedAt: null,
	usage: INITIAL_USAGE,
	health: INITIAL_HEALTH,
	lastEvent: null,
	recent: NO_EVENTS,
	timeline: NO_TIMELINE,
	spans: NO_SPANS,
	turns: NO_TURNS,
	turnsTotal: 0,
	actions: NO_ACTIONS,
	endedReason: null
});
/**
* Whether the session has shown anything at all.
*
* A surface that renders only when there is something to say uses this to stay
* completely absent for a session that never produced an event.
* @param state - current state.
* @returns true once any observation, durable or transient, has been folded.
*/
function hasLiveActivity(state) {
	return state.updatedAt !== null;
}
//#endregion
//#region src/client/styles.ts
/**
* Layout skeleton for the live-task view.
*
* Buttons, pills, tags and state dots come from the official primitives; what
* is left here is only the layout they deliberately do not own — the row grid
* and the view padding. Class names carry an `lt-` prefix so they cannot
* collide with the page's own generic names, and the stylesheet is injected
* once per document, tagged with the plugin id.
*
* The `--dsw-*` variables come from the host shell, so the view follows the
* active theme without duplicating any palette.
*/
const CSS = `
/* One place for the row grid: the rows, their header and the detail indentation
   all read these, so a column change cannot leave them out of line. */
.lt-view { display: flex; flex-direction: column; gap: 18px; padding: 18px 20px;
  --lt-col-time: 84px; --lt-col-kind: 44px; --lt-col-took: 64px; --lt-gap: 8px;
  /* Narrow windows narrow the columns instead of squeezing the payload, and the
     row keeps a floor so the timeline scrolls sideways rather than clipping. */
  container: lt-panel / inline-size; }
@container lt-panel (width <= 620px) {
  .lt-view { --lt-col-time: 50px; --lt-col-kind: 20px; }
  .lt-kindTag { padding: 0; justify-content: center; }
}
.lt-head { display: flex; align-items: center; gap: 8px; }
.lt-elapsed { margin-left: auto; color: var(--dsw-alias-label-tertiary); font-size: 12px; }

/* 模块：统一的标题层级与间距，让每块自成一段 */
.lt-section { display: flex; flex-direction: column; gap: 8px; }
.lt-sectionHead { display: flex; align-items: center; gap: 10px; }
.lt-sectionTitle { margin: 0; font: var(--dsw-font-xs-strong-13, 600 13px/18px inherit);
  color: var(--dsw-alias-label-secondary); user-select: none; }

/* 工具栏：与内置「轨迹」同样的控件位置（左搜索、右按钮），吸顶以保持可用 */
.lt-bar { position: sticky; top: 0; z-index: 2; display: flex; align-items: center; gap: 6px;
  padding: 4px 0; background: var(--dsw-alias-bg-base, #fff); }
.lt-search { flex: 1 1 220px; min-width: 140px; height: 26px; padding: 0 8px; border-radius: 6px;
  border: 1px solid var(--dsw-alias-separator, rgb(0 0 0 / 16%)); background: transparent;
  color: var(--dsw-alias-label-primary); font-size: 12px; }
.lt-barButton, .lt-barOn { height: 26px; padding: 0 9px; border: 0; border-radius: 6px; cursor: pointer;
  font-size: 12px; background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 5%));
  color: var(--dsw-alias-label-secondary); }
.lt-barOn { background: rgb(64 120 255 / 18%); color: var(--dsw-alias-label-primary); font-weight: 600; }
.lt-barHint { margin-left: auto; color: var(--dsw-alias-label-tertiary); font-size: 11px; }

/* 三泳道时间图：布局规格照内置「轨迹」（44px 标签列 / 50px 高 / span 8px / 泳道间距 14px） */
.lt-chartScroll { overflow-x: auto; overflow-y: hidden; padding-bottom: 2px; }
.lt-chart { display: grid; grid-template-columns: 44px minmax(0, 1fr); height: 50px; overflow: hidden;
  background: var(--dsw-alias-bg-layer-2, rgb(0 0 0 / 2%)); border-radius: 8px; }
.lt-chartLabels { position: relative; border-right: .5px solid var(--dsw-alias-border-l1, rgb(0 0 0 / 8%));
  color: var(--dsw-alias-label-tertiary); font-size: 10px; line-height: 1; }
.lt-chartLabels span { position: absolute; right: 3px; height: 8px; display: flex; align-items: center; }
.lt-chartLabels span:nth-child(1) { top: 7px; }
.lt-chartLabels span:nth-child(2) { top: 21px; }
.lt-chartLabels span:nth-child(3) { top: 35px; }
.lt-chartTrack { position: relative; overflow: hidden; cursor: crosshair; touch-action: none; }
.lt-chartLanes { position: absolute; top: 7px; bottom: 7px; left: 0; right: 0; z-index: 2; }
.lt-chartBoundaries { position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 3; pointer-events: none; }
.lt-chartSelection { position: absolute; top: 0; bottom: 0; z-index: 4; pointer-events: none;
  background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4078ff) 14%, transparent);
  border-left: 2px solid var(--dsw-alias-state-business-primary, #4078ff);
  border-right: 2px solid var(--dsw-alias-state-business-primary, #4078ff); }
.lt-chartBoundary { position: absolute; top: 0; bottom: 0; width: .5px; background: var(--dsw-alias-border-l2, rgb(0 0 0 / 12%)); }
.lt-span { position: absolute; height: 8px; min-width: 2px; padding: 0; border: 0; border-radius: 1px;
  cursor: pointer; opacity: .78; background: var(--dsw-alias-label-secondary); }
.lt-span[data-kind='user'] { background: var(--dsw-alias-state-business-primary, #4078ff); }
.lt-span[data-kind='context'] { background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #16a34a) 68%, var(--dsw-alias-label-secondary)); }
.lt-span[data-error='true'] { background: var(--dsw-alias-state-error-primary, #b42318); opacity: 1; }
.lt-span[data-selected='false'] { opacity: .2; }

/* 轮次横轴：宽度按该轮耗时分配（像素），超出宽度时横向滚动 */
.lt-axisScroll { overflow-x: auto; overflow-y: hidden; padding-bottom: 2px; }
.lt-axisScroll::-webkit-scrollbar { height: 8px; }
.lt-axisScroll::-webkit-scrollbar-thumb { background: var(--dsw-alias-separator, rgb(0 0 0 / 18%)); border-radius: 4px; }
.lt-axis { display: flex; gap: 2px; min-height: 26px; align-items: stretch; }
.lt-axisSegment, .lt-axisSegmentActive { position: relative; display: flex; align-items: center; justify-content: center;
  min-width: 30px; padding: 3px 6px; border: 0; border-radius: 5px; cursor: pointer;
  font-size: 11px; line-height: 16px; font-variant-numeric: tabular-nums;
  background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 6%)); color: var(--dsw-alias-label-secondary); }
.lt-axisSegmentActive { background: rgb(64 120 255 / 18%); color: var(--dsw-alias-label-primary); font-weight: 600; }
.lt-axisLabel { pointer-events: none; }
.lt-axisFailures { position: absolute; top: 1px; right: 3px; color: var(--dsw-alias-label-error, #b42318);
  font-size: 10px; font-weight: 700; }

/* 轮次明细：每轮一段，行可点开看参数与结果 */
.lt-turnList { display: flex; flex-direction: column; gap: 10px; }
/* 轮次导轨：与轨迹同规格（2px、accent 色、贯穿该轮所有行） */
.lt-turnSection, .lt-turnSectionActive { position: relative; padding: 2px 0 2px 12px; }
.lt-turnSection { border-left: 2px solid transparent; }
.lt-turnSectionActive { border-left: 2px solid transparent; }
.lt-turnSectionActive { border-left-color: var(--soia-turn-accent, color-mix(in srgb, var(--dsw-static-blue-500, #4078ff) 45%, transparent)); }
.lt-turnRail { position: absolute; left: 0; top: 0; bottom: 0; width: 2px;
  background: color-mix(in srgb, var(--dsw-static-blue-500, #4078ff) 22%, var(--dsw-alias-bg-layer-1, transparent)); }
.lt-turnHead { display: flex; align-items: center; gap: 8px; min-height: 26px; font-size: 12px; }
/* 轮次标签：与轨迹的 turnLabel 同规格（胶囊、字距、accent 背景） */
.lt-turnLabel, .lt-turnLabelActive { padding: 1px 6px; border-radius: 4px; font-size: 11px; font-weight: 650;
  letter-spacing: .035em; }
.lt-turnLabel { color: var(--dsw-alias-label-secondary); background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 4%)); }
.lt-turnLabelActive { color: var(--dsw-alias-label-primary);
  background: color-mix(in srgb, var(--dsw-static-blue-500, #4078ff) 22%, var(--dsw-alias-bg-layer-1, #fff)); }
.lt-turnMeta { color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }
/* The timeline scrolls as one pane, both ways: vertical for length, horizontal
   for a narrow window, where the rows keep a floor width instead of clipping. */
.lt-scroll { min-width: 0; max-height: 62vh; overflow: auto; }

/* ── Table structure, copied from the trajectory view ────────────────────────
   Same two-column table, same 30px rows, same half-pixel separators, same hover
   and selection tokens, same container-query widths. The panel is meant to look
   like a sibling of that view, so its numbers are taken from it rather than
   invented here. */
.lt-tablePane { box-sizing: border-box; min-width: 0; width: 100%; max-height: 62vh;
  position: relative; overflow: auto; container: lt-panel / inline-size; }
.lt-table { width: 100%; min-width: 640px; border-collapse: collapse; table-layout: fixed; }
.lt-table td { box-sizing: border-box; height: 30px; padding: 0 8px; overflow: hidden;
  border-bottom: .5px solid var(--dsw-alias-border-l1, rgb(0 0 0 / 8%));
  white-space: nowrap; text-overflow: ellipsis; vertical-align: middle; }
.lt-table tbody tr { transition: background-color .12s var(--ds-ease-in-out, ease-in-out); }
.lt-table tbody tr:hover { background: var(--dsw-alias-interactive-bg-hover, rgb(0 0 0 / 4%)); }
.lt-table tbody tr[data-selected='true'] { background: var(--dsw-alias-interactive-bg-active, rgb(64 120 255 / 10%)); }
.lt-table tbody tr[data-dim='true'] { opacity: .24; }
.lt-table tbody tr[data-picked='true'] { background: var(--dsw-alias-interactive-bg-active, rgb(64 120 255 / 10%)); }
.lt-table tbody tr[data-turn-start='true'] td { position: relative; overflow: visible; }
.lt-table tbody tr[data-turn-start='true']:not(:first-child) td::before {
  content: ''; position: absolute; inset: 0 0 auto; height: 2px; transform: translateY(-50%);
  background: var(--dsw-alias-border-l1, rgb(0 0 0 / 8%)); pointer-events: none; z-index: 1; }
.lt-eventColumn { width: 84px; }
@container lt-panel (width <= 620px) {
  /* The trajectory view narrows this column to 50px because its chip is a 13px
     icon there; ours is a word, so it narrows less — the row still scrolls
     sideways rather than clipping. */
  .lt-eventColumn { width: 64px; }
  .lt-kindTag { padding: 0 4px; }
  .lt-tlEntryId { display: none; }
}
.lt-eventCell { position: relative; overflow: visible; padding-left: 12px !important; padding-right: 4px !important; }
/* The trajectory view puts a dot at the left of every row, on the same vertical
   line the turn rail runs down; without it the gutter reads as empty space. */
.lt-eventCell::after { content: ''; position: absolute; left: 15px; top: 50%; width: 4px; height: 4px;
  border-radius: 50%; transform: translateY(-50%); background: var(--dsw-alias-label-caption); pointer-events: none; }
.lt-turnRow .lt-eventCell::after { display: none; }
.lt-contentColumn { width: auto; }
.lt-contentCell { min-width: 0; color: var(--dsw-alias-label-primary); padding-left: 4px !important; }
.lt-rowButton { display: flex; align-items: center; gap: 6px; width: 100%; height: 30px; padding: 0;
  border: 0; background: transparent; text-align: left; font-size: 12.5px; line-height: 20px; cursor: pointer; }
.lt-rowButton:focus-visible { outline: none; box-shadow: inset 0 0 0 1px var(--dsw-alias-state-business-primary); }
.lt-turnRow td { height: 26px; }
.lt-turnRail { position: absolute; left: 0; top: -1px; bottom: -1px; width: 2px; z-index: 4;
  background: var(--soia-turn-accent, color-mix(in srgb, var(--dsw-static-blue-500, #4078ff) 22%, var(--dsw-alias-bg-layer-1, #fff))); }
.lt-stepRow td { height: 22px; border-bottom: 0; }
.lt-stepLabel { color: var(--dsw-alias-label-tertiary); font-size: 11px; font-weight: 600; letter-spacing: .03em; }
.lt-detailRow > td { height: auto; white-space: normal; padding: 0 !important; border-bottom: .5px solid var(--dsw-alias-border-l1, rgb(0 0 0 / 8%)); }
.lt-detailCell { background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 3%)); }
.lt-turnMeta { margin-right: 12px; }

/* ── Panes and the detail drawer ────────────────────────────────────────────
   The trajectory view opens a row's detail as a right-hand pane with a 42px
   header, a tab strip and a scrolling body; an inline block under the row pushed
   every later row down and could not be read against the row it described. */
.lt-panes { display: flex; align-items: flex-start; gap: 16px; min-width: 0; }
.lt-paneMain { display: flex; flex-direction: column; gap: 18px; flex: 1; min-width: 0; }
.lt-details { display: flex; flex-direction: column; flex: none; width: 380px; max-height: 78vh;
  /* The shell scrolls the whole view; without this the tab strip rides up out of
     the viewport (measured at y=-94 on a live session) and the drawer cannot be
     used without scrolling back to the top. The trajectory view keeps its pane
     pinned the same way. */
  position: sticky; top: 8px; align-self: flex-start; z-index: 1;
  border: 1px solid var(--dsw-alias-border-l1, rgb(0 0 0 / 8%)); border-radius: 8px;
  background: var(--dsw-alias-bg-layer-1, #fff); overflow: hidden; }
.lt-detailsHeader { display: flex; align-items: center; justify-content: space-between; gap: 8px;
  box-sizing: border-box; height: 42px; padding: 0 8px 0 12px; flex: none;
  border-bottom: .5px solid var(--dsw-alias-border-l2, rgb(0 0 0 / 14%)); }
.lt-detailsTitle { display: flex; align-items: center; gap: 8px; min-width: 0; color: var(--dsw-alias-label-primary); }
.lt-detailsName { font-weight: 600; }
.lt-detailsLocation { min-width: 0; color: var(--dsw-alias-label-tertiary);
  font: 11px/16px var(--dsw-font-mono, monospace); text-overflow: ellipsis; white-space: nowrap; overflow: hidden; }
.lt-detailsClose { flex: none; width: 22px; height: 22px; border: 0; border-radius: 4px; cursor: pointer;
  background: transparent; color: var(--dsw-alias-label-tertiary); font-size: 15px; line-height: 1; }
.lt-detailsClose:hover { background: var(--dsw-alias-interactive-bg-hover, rgb(0 0 0 / 6%)); }
.lt-detailTabs { display: flex; flex: none; overflow-x: auto; border-bottom: .5px solid var(--dsw-alias-border-l1, rgb(0 0 0 / 8%)); }
.lt-detailTabs::-webkit-scrollbar { display: none; }
.lt-detailTab, .lt-detailTabActive { flex: none; position: relative; padding: 6px 9px; border: 0;
  background: transparent; cursor: pointer; font: var(--dsw-font-xs-13, 13px/18px inherit); }
.lt-detailTab { color: var(--dsw-alias-label-tertiary); }
.lt-detailTabActive { color: var(--dsw-alias-state-business-primary, #4078ff); }
.lt-detailTabActive::after { content: ''; position: absolute; bottom: 0; left: 9px; right: 9px; height: 2px;
  border-radius: 1px 1px 0 0; background: var(--dsw-alias-state-business-primary, #4078ff); }
.lt-detailBody { flex: 1; min-height: 0; overflow: auto; padding: 10px 12px; }
.lt-detailBody .lt-detailPre { max-height: none; }
.lt-toolList { display: flex; flex-direction: column; margin: 4px 0 0; padding: 0; list-style: none; }
.lt-toolItem { display: flex; flex-direction: column; }
/* Rows follow the trajectory view's table: one 30px line each, a half-pixel
   separator, no card chrome. Floating rounded rows read as a different product. */
.lt-toolButton { display: grid;
  grid-template-columns: var(--lt-col-time) var(--lt-col-kind) minmax(0, 1fr) var(--lt-col-took) 12px;
  align-items: center; gap: var(--lt-gap);
  box-sizing: border-box; width: 100%; height: 30px; padding: 0 8px;
  border: 0; border-bottom: .5px solid var(--dsw-alias-border-l1, rgb(0 0 0 / 8%));
  border-radius: 0; background: transparent;
  text-align: left; font-size: 12.5px; line-height: 20px; cursor: pointer;
  transition: background-color .12s var(--ds-ease-in-out, ease-in-out); }
.lt-toolButton:hover { background: var(--dsw-alias-interactive-bg-hover, rgb(0 0 0 / 4%)); }
.lt-toolButton[data-selected='true'] { background: var(--dsw-alias-interactive-bg-active, rgb(64 120 255 / 10%)); }
/* A row outside the selected range dims the way the trajectory view dims its own. */
.lt-toolItem[data-dim='true'] { opacity: .24; }

/* 类型徽标：照抄轨迹 kindSlot / kindTag 的规格（中文槽宽 44px、标签高 19px、圆角 4px、10px/650、字距 .035em） */
.lt-kindSlot { display: flex; justify-content: flex-end; align-items: center; width: 44px; flex: none; }
.lt-kindTag { box-sizing: border-box; display: inline-flex; align-items: center; height: 19px; padding: 0 5px;
  border: 1px solid transparent; border-radius: 4px; font-size: 10px; font-weight: 650; line-height: 16px;
  letter-spacing: .035em; user-select: none; white-space: nowrap;
  color: var(--dsw-alias-label-secondary); background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 6%)); }
.lt-kindTag[data-kind='user'] { color: var(--dsw-alias-state-business-primary, #2b5cd9);
  background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4078ff) 14%, transparent); }
.lt-kindTag[data-kind='context'] { color: var(--dsw-alias-state-success-primary, #18794e);
  background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #16a34a) 14%, transparent); }
.lt-kindTag[data-kind='assistant'] { color: var(--dsw-alias-brand-primary-new-colorprimary-new-color, #6b4bd6);
  background: color-mix(in srgb, var(--dsw-alias-brand-primary-new-colorprimary-new-color, #7c5cff) 14%, transparent); }
.lt-kindTag[data-kind='tool'] { color: var(--dsw-alias-state-warn-label, #96540a);
  background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d97706) 16%, transparent); }
/* Failure wins over the kind tint: the row's outcome is what a reader scans for. */
.lt-kindTag[data-kind][data-failed='true'] { color: var(--dsw-alias-state-error-primary, #b42318);
  background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #b42318) 16%, transparent); }
.lt-toolButton:hover { background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 4%)); }
.lt-toolHint { color: var(--dsw-alias-label-tertiary); font-size: 11px; white-space: nowrap; }
.lt-toolDetail { display: flex; flex-direction: column; gap: 10px;
  /* Indented to the payload column, computed from the same grid constants. */
  margin: 4px 0 10px calc(var(--lt-col-time) + var(--lt-col-kind) + var(--lt-gap) * 2 + 6px);
  padding: 10px 12px; border-radius: 8px; border: 1px solid var(--dsw-alias-separator, rgb(0 0 0 / 8%));
  background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 3%)); }
.lt-detailBlock { display: flex; flex-direction: column; gap: 4px; min-width: 0; }
.lt-detailLabel { color: var(--dsw-alias-label-tertiary); font-size: 11px; }
.lt-detailPre { margin: 0; max-height: 168px; overflow: auto; padding: 6px 8px; border-radius: 6px;
  background: var(--dsw-alias-bg-layer-1, #fff); white-space: pre-wrap; word-break: break-word;
  font-family: var(--dsw-font-mono, monospace); font-size: 12px; line-height: 18px;
  color: var(--dsw-alias-label-primary); }
.lt-summaryLine { margin: -6px 0 0; color: var(--dsw-alias-label-secondary); font-size: 12.5px; }
.lt-usageLine { margin: -2px 0 0; color: var(--dsw-alias-label-tertiary); font-size: 12px;
  font-variant-numeric: tabular-nums; }

/* 时间线：一条导轨 + 每行一个事件，视觉语言与内置「轨迹」一致 */
.lt-timeline { margin: 0; padding: 0; list-style: none; }
.lt-tlRow, .lt-tlTurn { display: grid; align-items: baseline; gap: 8px; font-size: 12.5px; line-height: 20px; }
.lt-tlRow { grid-template-columns: 18px 62px 40px 1fr auto; padding: 3px 0; }
.lt-tlTurn { grid-template-columns: 18px 1fr; padding: 10px 0 4px; }
.lt-tlRail { position: relative; display: flex; align-items: center; justify-content: center; align-self: stretch; }
.lt-tlRail::before { content: ''; position: absolute; top: 0; bottom: 0; left: 50%; width: 1px;
  background: var(--dsw-alias-separator, rgb(0 0 0 / 10%)); transform: translateX(-50%); }
.lt-tlRow:first-child .lt-tlRail::before { top: 50%; }
.lt-tlRow:last-child .lt-tlRail::before { bottom: 50%; }
.lt-tlRail > * { position: relative; z-index: 1; background: var(--dsw-alias-bg-base, #fff); border-radius: 50%; }
.lt-tlTurnDot { position: relative; z-index: 1; width: 5px; height: 5px; border-radius: 50%;
  background: var(--dsw-alias-label-tertiary); }
.lt-tlTurnLabel { font-weight: 600; color: var(--dsw-alias-label-secondary); font-size: 12px; }
.lt-tlTime { color: var(--dsw-alias-label-caption); font-family: var(--dsw-font-mono, monospace);
  font-variant-numeric: tabular-nums; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.lt-tlBadge, .lt-tlBadgeTool { display: inline-block; padding: 0 5px; border-radius: 5px; font-size: 11px;
  line-height: 16px; text-align: center; }
.lt-tlBadge { color: var(--dsw-alias-label-tertiary); background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 5%)); }
.lt-tlBadgeTool { color: var(--dsw-alias-label-secondary); background: rgb(64 120 255 / 10%); }
.lt-tlBody { display: flex; align-items: baseline; gap: 6px; min-width: 0; }
.lt-tlTitle { flex: none; font-weight: 600; font-family: var(--dsw-font-mono, monospace);
  color: var(--dsw-alias-label-primary); }
.lt-tlEntryId { flex: none; color: var(--dsw-alias-label-tertiary); font-size: 11px;
  font-family: var(--dsw-font-mono, monospace); }
.lt-detailMono { font-family: var(--dsw-font-mono, monospace); }
.lt-tlArgs { flex: none; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  color: var(--dsw-alias-label-secondary); font-family: var(--dsw-font-mono, monospace); }
.lt-tlDetail, .lt-tlResult { min-width: 0; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;
  font-family: var(--dsw-font-mono, monospace); }
.lt-tlDetail { color: var(--dsw-alias-label-secondary); max-width: 42%; }
.lt-tlArrow { flex: none; color: var(--dsw-alias-label-tertiary); }
.lt-tlResult { color: var(--dsw-alias-label-primary); }
.lt-tlTook, .lt-tlTookFailed { white-space: nowrap; font-size: 11.5px; font-variant-numeric: tabular-nums;
  min-width: 64px; text-align: right; }
.lt-tlTook { color: var(--dsw-alias-label-tertiary); }
.lt-tlTookFailed { color: var(--dsw-alias-label-error, #b42318); }

/* 会话头指示器：在 对话/轨迹 页也能看到当前工具 */
.lt-headerChip { display: inline-flex; align-items: center; gap: 5px; min-height: 24px; padding: 2px 8px;
  border: 0; border-radius: 999px; background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 5%));
  color: var(--dsw-alias-label-secondary); font-size: 12px; line-height: 18px; cursor: default; }
.lt-headerChipLabel { font-family: var(--dsw-font-mono, monospace); }

/* 顶部工具行：不展开表格也能看到"现在用哪个工具" */
.lt-toolLine { display: flex; align-items: baseline; gap: 8px; margin: -4px 0 0; }
.lt-toolLineLabel { font-size: 11.5px; color: var(--dsw-alias-label-tertiary); }
.lt-toolLineValue { font-size: 13px; font-weight: 600; font-family: var(--dsw-font-mono, monospace);
  color: var(--dsw-alias-label-primary); }

/* 模块一：概览卡网格 */
.lt-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(132px, 1fr)); gap: 8px; }
.lt-stat { display: flex; flex-direction: column; gap: 3px; padding: 9px 11px; border-radius: 10px;
  background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 4%)); }
.lt-statLabel { font-size: 11.5px; color: var(--dsw-alias-label-tertiary); }
.lt-statValue { font-size: 15px; font-weight: 600; color: var(--dsw-alias-label-primary);
  font-variant-numeric: tabular-nums; }
.lt-statValueFailed { font-size: 15px; font-weight: 600; color: var(--dsw-alias-label-error, #b42318); }

/* 模块二：正在跑 */
.lt-list { display: flex; flex-direction: column; gap: 4px; margin: 0; padding: 0; list-style: none; }
.lt-call { display: grid; grid-template-columns: 10px 150px 1fr auto; align-items: center; gap: 8px;
  padding: 8px 10px; border-radius: 8px; font-size: 13px; line-height: 18px;
  background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 4%)); }
.lt-callTook { color: var(--dsw-alias-label-tertiary); font-size: 12px; }

/* 轮次内的步骤分组（与轨迹一致） */
.lt-stepGroup { display: flex; flex-direction: column; }
.lt-stepLabel { margin: 6px 0 2px 6px; color: var(--dsw-alias-label-tertiary); font-size: 11px;
  letter-spacing: .02em; }

/* 详情：概览网格 + 参数/结果 */
.lt-detailGrid { display: grid; grid-template-columns: 72px minmax(0, 1fr); gap: 3px 12px; margin: 0; }
.lt-detailGrid dt { color: var(--dsw-alias-label-tertiary); }
.lt-detailGrid dd { margin: 0; color: var(--dsw-alias-label-primary); }

/* 模块三：动作日志 */
.lt-filters { margin-left: auto; display: flex; gap: 4px; }
.lt-filter, .lt-filterActive { padding: 2px 8px; border: 0; border-radius: 999px; cursor: pointer;
  font-size: 11.5px; line-height: 18px; }
.lt-filter { color: var(--dsw-alias-label-tertiary); background: transparent; }
.lt-filter:hover { background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 5%)); }
.lt-filterActive { color: var(--dsw-alias-label-primary); background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 7%)); }
.lt-table { width: 100%; border-collapse: collapse; font-size: 12.5px; line-height: 18px; }
.lt-th { padding: 4px 8px; text-align: left; font-weight: 600; color: var(--dsw-alias-label-tertiary);
  border-bottom: 1px solid var(--dsw-alias-separator, rgb(0 0 0 / 8%)); white-space: nowrap; }
.lt-table tbody tr:nth-child(odd) { background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 3%)); }
.lt-rowFailed { background: rgb(180 35 24 / 6%) !important; }
.lt-tdTime { padding: 5px 8px; color: var(--dsw-alias-label-tertiary); font-family: var(--dsw-font-mono, monospace); white-space: nowrap; }
.lt-tdTool { padding: 5px 8px; white-space: nowrap; }
.lt-tdWhat { padding: 5px 8px; max-width: 260px; }
.lt-tdTook { padding: 5px 8px; color: var(--dsw-alias-label-tertiary); white-space: nowrap; font-variant-numeric: tabular-nums; }
.lt-tdResult { padding: 5px 8px; }
.lt-resultLine { display: block; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;
  max-width: 260px; color: var(--dsw-alias-label-primary); }
.lt-badgeOk, .lt-badgeFailed { display: inline-block; margin-top: 2px; padding: 0 6px; border-radius: 6px;
  font-size: 11px; line-height: 16px; }
.lt-badgeOk { color: var(--dsw-alias-label-tertiary); background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 5%)); }
.lt-badgeFailed { color: var(--dsw-alias-label-error, #b42318); background: rgb(180 35 24 / 10%); }

/* 模块五：运行状况 */
.lt-health { display: flex; flex-wrap: wrap; gap: 4px 14px; font-size: 12px; line-height: 18px;
  color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }
.lt-healthStale { color: var(--dsw-alias-label-error, #b42318); }

/* 共用 */
.lt-toolName { color: var(--dsw-alias-label-primary); font-weight: 600; font-family: var(--dsw-font-mono, monospace); }
.lt-callDetail, .lt-tdWhat { min-width: 0; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;
  font-family: var(--dsw-font-mono, monospace); color: var(--dsw-alias-label-secondary); }
.lt-none { margin: 0; color: var(--dsw-alias-label-tertiary); font-size: 12.5px; }
.lt-empty { display: flex; align-items: center; gap: 8px; padding: 24px 20px;
  color: var(--dsw-alias-label-tertiary); font-size: 13px; }
`;
/** Class names this view applies. */
const styles = {
	view: "lt-view",
	head: "lt-head",
	elapsed: "lt-elapsed",
	headerChip: "lt-headerChip",
	headerChipLabel: "lt-headerChipLabel",
	toolLine: "lt-toolLine",
	toolLineLabel: "lt-toolLineLabel",
	toolLineValue: "lt-toolLineValue",
	section: "lt-section",
	sectionHead: "lt-sectionHead",
	sectionTitle: "lt-sectionTitle",
	stats: "lt-stats",
	stat: "lt-stat",
	statLabel: "lt-statLabel",
	statValue: "lt-statValue",
	statValueFailed: "lt-statValueFailed",
	list: "lt-list",
	call: "lt-call",
	callDetail: "lt-callDetail",
	callTook: "lt-callTook",
	filters: "lt-filters",
	filter: "lt-filter",
	filterActive: "lt-filterActive",
	table: "lt-table",
	th: "lt-th",
	rowFailed: "lt-rowFailed",
	tdTime: "lt-tdTime",
	tdTool: "lt-tdTool",
	tdWhat: "lt-tdWhat",
	tdTook: "lt-tdTook",
	tdResult: "lt-tdResult",
	resultLine: "lt-resultLine",
	badgeOk: "lt-badgeOk",
	badgeFailed: "lt-badgeFailed",
	bar: "lt-bar",
	search: "lt-search",
	barButton: "lt-barButton",
	barOn: "lt-barOn",
	barHint: "lt-barHint",
	axisScroll: "lt-axisScroll",
	stepGroup: "lt-stepGroup",
	stepLabel: "lt-stepLabel",
	detailGrid: "lt-detailGrid",
	detailBlock: "lt-detailBlock",
	detailLabel: "lt-detailLabel",
	detailPre: "lt-detailPre",
	chartScroll: "lt-chartScroll",
	chart: "lt-chart",
	chartLabels: "lt-chartLabels",
	chartTrack: "lt-chartTrack",
	chartLanes: "lt-chartLanes",
	chartBoundaries: "lt-chartBoundaries",
	chartBoundary: "lt-chartBoundary",
	chartSelection: "lt-chartSelection",
	span: "lt-span",
	axis: "lt-axis",
	axisSegment: "lt-axisSegment",
	axisSegmentActive: "lt-axisSegmentActive",
	axisLabel: "lt-axisLabel",
	axisFailures: "lt-axisFailures",
	turnList: "lt-turnList",
	turnSection: "lt-turnSection",
	turnSectionActive: "lt-turnSectionActive",
	turnHead: "lt-turnHead",
	turnMeta: "lt-turnMeta",
	toolList: "lt-toolList",
	tablePane: "lt-tablePane",
	eventColumn: "lt-eventColumn",
	contentColumn: "lt-contentColumn",
	row: "lt-row",
	eventCell: "lt-eventCell",
	contentCell: "lt-contentCell",
	rowButton: "lt-rowButton",
	turnRow: "lt-turnRow",
	stepRow: "lt-stepRow",
	detailRow: "lt-detailRow",
	detailCell: "lt-detailCell",
	turnBody: "lt-turnBody",
	panes: "lt-panes",
	paneMain: "lt-paneMain",
	details: "lt-details",
	detailsHeader: "lt-detailsHeader",
	detailsTitle: "lt-detailsTitle",
	detailsName: "lt-detailsName",
	detailsLocation: "lt-detailsLocation",
	detailsClose: "lt-detailsClose",
	detailTabs: "lt-detailTabs",
	detailTab: "lt-detailTab",
	detailTabActive: "lt-detailTabActive",
	detailBody: "lt-detailBody",
	scroll: "lt-scroll",
	rowsInner: "lt-rowsInner",
	toolItem: "lt-toolItem",
	toolButton: "lt-toolButton",
	toolHint: "lt-toolHint",
	kindSlot: "lt-kindSlot",
	kindTag: "lt-kindTag",
	turnRail: "lt-turnRail",
	turnLabel: "lt-turnLabel",
	turnLabelActive: "lt-turnLabelActive",
	toolDetail: "lt-toolDetail",
	summaryLine: "lt-summaryLine",
	usageLine: "lt-usageLine",
	timeline: "lt-timeline",
	tlRow: "lt-tlRow",
	tlTurn: "lt-tlTurn",
	tlRail: "lt-tlRail",
	tlTurnDot: "lt-tlTurnDot",
	tlTurnLabel: "lt-tlTurnLabel",
	tlTime: "lt-tlTime",
	tlBadge: "lt-tlBadge",
	tlBadgeTool: "lt-tlBadgeTool",
	tlBody: "lt-tlBody",
	tlTitle: "lt-tlTitle",
	tlEntryId: "lt-tlEntryId",
	tlArgs: "lt-tlArgs",
	detailMono: "lt-detailMono",
	tlDetail: "lt-tlDetail",
	tlArrow: "lt-tlArrow",
	tlResult: "lt-tlResult",
	tlTook: "lt-tlTook",
	tlTookFailed: "lt-tlTookFailed",
	health: "lt-health",
	healthStale: "lt-healthStale",
	toolName: "lt-toolName",
	none: "lt-none",
	empty: "lt-empty"
};
/** Plugin id the injected style tag is tagged with. */
const STYLE_TAG_ID = "ui-live-tasks";
if (typeof document !== "undefined" && document.querySelector(`style[data-plugin-css="${STYLE_TAG_ID}"]`) === null) {
	const tag = document.createElement("style");
	tag.dataset.plugin = STYLE_TAG_ID;
	tag.dataset.pluginCss = STYLE_TAG_ID;
	tag.textContent = CSS;
	document.head.append(tag);
}
//#endregion
//#region src/client/LiveTasksHeaderAction.tsx
/**
* A compact companion to the view: the tool the session is using right now,
* shown in the session header so it is visible from any view.
*
* The view tab answers "what is it doing" in full, but only for a reader who is
* already looking at that tab. "Which tool is it on" is worth one line
* everywhere else — including in the 对话 view, where a long silent turn is
* exactly when the question gets asked.
*
* Renders nothing when the session has shown no activity, so a fresh session
* gains no chrome.
*
* @module soia-dsh-client-ui-live-tasks/client/header-action
*/
/**
* Render the running-tool indicator.
* @param props - projection hook and translator from the slot kit.
* @returns the indicator, or null when there is nothing to report.
*/
function LiveTasksHeaderAction({ useProjection, t }) {
	const state = useProjection("liveTask");
	if (state === void 0 || !hasLiveActivity(state)) return null;
	const inFlight = state.openTools.length > 0;
	const label = inFlight ? state.openTools.map((call) => call.name).join(", ") : state.actions.at(-1)?.name ?? t("view.tab");
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("button", {
		type: "button",
		className: styles.headerChip,
		"aria-label": `${inFlight ? t("head.toolRunning") : t("head.toolLast")}: ${label}`,
		onClick: () => {
			globalThis.location.hash = "";
		},
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.StateDot, {
			state: inFlight ? "ongoing" : "idle",
			size: 8
		}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
			className: styles.headerChipLabel,
			children: label
		})]
	});
}
//#endregion
//#region src/client/LiveTasksView.tsx
/**
* The `conversation.view` entry: the session as a timeline.
*
* ## Why a timeline
*
* Three earlier versions showed counts, then a table, then modules of cards.
* Each asked the reader to assemble the story from parallel lists, and two of
* them were rejected on sight for exactly that. A long task is one narrative —
* your message, the model's reply, a tool call, its result, the next call — and
* the built-in 轨迹 view already renders a session that way, so this panel
* borrows the idiom rather than inventing a second one for the same data.
*
* ## Architecture
*
* It deliberately mirrors the built-in 轨迹 view, because two views over one
* session should not teach two visual languages:
*
*   工具栏        搜索 / 展开全部 / 只看失败 — the same controls over the same data
*   轮次横轴      one segment per turn, width by duration, in a strip that
*                 scrolls sideways when a session has more turns than width
*   轮次明细      per turn: which tools ran, with the payload inline; clicking a
*                 row opens its full arguments and result, like a 轨迹 row
*   运行状况      the panel's own counters, so a stale panel is visible as stale
*
* @module soia-dsh-client-ui-live-tasks/client/view
*/
/**
* Re-render once a second so elapsed times stay true.
* @returns the current epoch milliseconds.
*/
function useNow() {
	const [now, setNow] = (0, react.useState)(() => Date.now());
	(0, react.useEffect)(() => {
		const timer = setInterval(() => setNow(Date.now()), 1e3);
		return () => clearInterval(timer);
	}, []);
	return now;
}
/**
* Render a token count compactly: `1234567` → `1.23M`.
*
* Six-digit numbers repeated down a column are hard to compare at a glance;
* the exact value stays available in the tooltip.
* @param value - token count.
* @returns the compact form.
*/
function compact(value) {
	if (value < 1e3) return String(value);
	if (value < 1e6) return `${(value / 1e3).toFixed(1)}k`;
	return `${(value / 1e6).toFixed(2)}M`;
}
/**
* Render a tool's arguments the way the trajectory view does: the first pair as
* `key: "value"`, muted and monospaced, inside parentheses — not my summarizer's
* `a @ b` which no other view in the product speaks.
* @param entry - the row to read.
* @returns the inline argument text, or null when there is nothing to show.
*/
function argsInline(entry) {
	if (entry.kind !== "tool") return null;
	if (entry.argsFull !== null) try {
		const parsed = JSON.parse(entry.argsFull);
		if (parsed !== null && typeof parsed === "object") {
			const first = Object.entries(parsed)[0];
			if (first !== void 0) {
				const [key, value] = first;
				return `${key}: ${typeof value === "string" ? value : JSON.stringify(value)}`;
			}
		}
	} catch {}
	return entry.detail;
}
/**
* `YYYY-MM-DD HH:MM:SS.mmm`, local time — the precision the trajectory view's
* timing panel shows; second resolution hides the very differences timing exists
* to reveal.
* @param time - epoch milliseconds.
* @returns the stamp.
*/
function stampOf(time) {
	const date = new Date(time);
	const pad = (value, width = 2) => String(value).padStart(width, "0");
	return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}.${pad(date.getMilliseconds(), 3)}`;
}
/** Elapsed milliseconds as a group-separated integer. */
function millisBetween(from, to) {
	return new Intl.NumberFormat("zh-CN").format(Math.max(0, to - from));
}
/** Wall-clock `HH:MM:SS` in the reader's own timezone. */
function clockOf(at) {
	return new Date(at).toLocaleTimeString(void 0, { hour12: false });
}
/** Whole seconds between two instants, floored at zero. */
function secondsBetween(from, to) {
	return Math.max(0, Math.round((to - from) / 1e3));
}
/**
* The session's three lanes over time, drawn the way the built-in 轨迹 view draws
* them: absolute spans positioned by CSS custom properties inside a track, with
* 0.5px turn boundaries, and one colour per lane (context gets its own tint, as
* it does there).
*
* The lanes answer a question a list cannot: where the time went. A turn that is
* all tools, a turn that is all model, and a long context injection are three
* different shapes at a glance.
*
* @param props - the rows to plot, the turns to mark, and the interaction state.
* @returns the chart.
*/
function LaneChart({ spans, turns, now, selected, range, t, onSelect, onRange }) {
	const [drag, setDrag] = (0, react.useState)(null);
	const plotted = spans;
	const starts = plotted.map((segment) => segment.startedAt);
	const ends = plotted.map((segment) => segment.endedAt ?? now);
	const from = starts.length === 0 ? now - 1e3 : Math.min(...starts);
	const to = Math.max(now, ...ends.length === 0 ? [now] : ends);
	const span = Math.max(1e3, to - from);
	const at = (time) => (time - from) / span * 100;
	const laneOf = (kind) => kind === "assistant" ? 1 : kind === "tool" ? 2 : 0;
	return /* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
		className: styles.chartScroll,
		children: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
			className: styles.chart,
			style: { minWidth: `560px` },
			children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
				className: styles.chartLabels,
				"aria-hidden": "true",
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: t("lane.input") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: t("lane.model") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: t("lane.tools") })
				]
			}), /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
				className: styles.chartTrack,
				onPointerDown: (event) => {
					const rect = event.currentTarget.getBoundingClientRect();
					const pct = (event.clientX - rect.left) / rect.width * 100;
					setDrag({
						startPct: pct,
						endPct: pct
					});
					event.currentTarget.setPointerCapture(event.pointerId);
				},
				onPointerMove: (event) => {
					if (drag === null) return;
					const rect = event.currentTarget.getBoundingClientRect();
					const pct = (event.clientX - rect.left) / rect.width * 100;
					setDrag({
						startPct: drag.startPct,
						endPct: pct
					});
				},
				onPointerUp: () => {
					if (drag === null) return;
					const lo = Math.min(drag.startPct, drag.endPct);
					const hi = Math.max(drag.startPct, drag.endPct);
					onRange(hi - lo < 1.5 ? null : {
						from: from + lo / 100 * span,
						to: from + hi / 100 * span
					});
					setDrag(null);
				},
				children: [
					range !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
						className: styles.chartSelection,
						style: {
							left: `${at(range.from)}%`,
							width: `${Math.max(.2, at(range.to) - at(range.from))}%`
						},
						"aria-hidden": "true"
					}),
					drag !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
						className: styles.chartSelection,
						"data-dragging": "true",
						style: {
							left: `${Math.min(drag.startPct, drag.endPct)}%`,
							width: `${Math.max(.2, Math.abs(drag.endPct - drag.startPct))}%`
						},
						"aria-hidden": "true"
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
						className: styles.chartLanes,
						children: plotted.map((segment) => /* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
							type: "button",
							className: styles.span,
							"data-kind": segment.kind,
							"data-error": segment.status === "failed",
							"data-selected": selected === null || selected === segment.turn,
							style: {
								top: `${laneOf(segment.kind) * 14}px`,
								left: `${at(segment.startedAt)}%`,
								width: `max(2px, ${Math.max(.2, at(segment.endedAt ?? now) - at(segment.startedAt))}%)`
							},
							title: `${segment.kind} · ${clockOf(segment.startedAt)}`,
							"aria-label": `${segment.kind} · ${clockOf(segment.startedAt)}`,
							onClick: () => onSelect(segment.turn)
						}, segment.id))
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
						className: styles.chartBoundaries,
						"aria-hidden": "true",
						children: turns.map((turn) => /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.chartBoundary,
							style: { left: `${at(turn.startedAt)}%` }
						}, turn.turn))
					})
				]
			})]
		})
	});
}
/** One tool row inside a turn, expandable to its arguments and result. */
function ToolRow({ entry, now, showClock, turnStart, expanded, selected, dim, onToggle, t }) {
	const running = entry.status === "running";
	const failed = entry.status === "failed";
	const took = secondsBetween(entry.startedAt, entry.endedAt ?? now);
	const kind = entry.kind === "tool" ? t("timeline.tool") : entry.kind === "user" ? t("timeline.user") : entry.kind === "context" ? t("lane.context") : t("timeline.assistant");
	const clock = showClock ? clockOf(entry.startedAt) : `+${secondsBetween(turnStart, entry.startedAt)}s`;
	return /* @__PURE__ */ (0, react_jsx_runtime.jsx)(react_jsx_runtime.Fragment, { children: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("tr", {
		className: styles.row,
		"data-kind": entry.kind,
		"data-error": failed || void 0,
		"data-selected": selected || void 0,
		"data-dim": dim || void 0,
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("td", {
			className: styles.eventCell,
			"aria-label": kind,
			children: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: styles.kindSlot,
				children: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
					className: styles.kindTag,
					"data-kind": entry.kind,
					"data-failed": failed,
					children: kind
				})
			})
		}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("td", {
			className: styles.contentCell,
			children: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("button", {
				type: "button",
				className: styles.rowButton,
				onClick: onToggle,
				"aria-expanded": expanded,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlTime,
						children: clock
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlTitle,
						children: entry.kind === "tool" ? entry.title : ""
					}),
					(entry.entryId ?? null) !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlEntryId,
						children: entry.entryId
					}),
					entry.kind === "tool" && argsInline(entry) !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlArgs,
						title: argsInline(entry) ?? "",
						children: `（${argsInline(entry)}）`
					}),
					entry.kind !== "tool" && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlDetail,
						title: entry.detail ?? "",
						children: entry.detail === null || entry.detail === "" ? t("timeline.toolCallsOnly") : entry.detail
					}),
					entry.result !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsxs)(react_jsx_runtime.Fragment, { children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlArrow,
						"aria-hidden": "true",
						children: "→"
					}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlResult,
						title: entry.result,
						children: entry.result
					})] }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: failed ? styles.tlTookFailed : styles.tlTook,
						children: entry.kind !== "tool" ? "" : `${running ? t("status.running") : failed ? t("status.failed") : t("status.ok")} ${t("time.seconds", { s: took })}`
					})
				]
			})
		})]
	}) });
}
/**
* Group a turn's rows by step, the way the trajectory view does.
*
* Rows keep their order inside a step; a row without a step number (a message
* between steps) forms its own group, so nothing is dropped or reordered.
* @param entries - the turn's rows in order.
* @returns groups of rows, each labelled with its step or null.
*/
function groupByStep(entries) {
	const groups = [];
	for (const entry of entries) {
		const last = groups.at(-1);
		if (last !== void 0 && last.step === entry.step) last.rows.push(entry);
		else groups.push({
			step: entry.step,
			rows: [entry]
		});
	}
	return groups;
}
/**
* One turn as a table body: a header row, then one row per record.
*
* Multiple `tbody` elements in one table are valid HTML, and this keeps the turn
* boundaries — and the rail that marks them — inside the table, the way the
* trajectory view draws them.
*/
function TurnSection({ turn, entries, picked, now, showClock, open, expandedId, dimmed, onToggle, t }) {
	const started = clockOf(turn.startedAt);
	const took = secondsBetween(turn.startedAt, turn.endedAt ?? now);
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("tbody", {
		className: styles.turnBody,
		"data-turn": turn.turn,
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("tr", {
			className: styles.turnRow,
			"data-turn-start": "true",
			"data-picked": picked || void 0,
			children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("td", {
				className: styles.eventCell,
				children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
					className: styles.turnRail,
					"aria-hidden": "true"
				}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("strong", {
					className: styles.turnLabel,
					children: t("timeline.turnN", { n: turn.turn })
				})]
			}), /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("td", {
				className: styles.contentCell,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.turnMeta,
						children: started
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.turnMeta,
						children: t("time.seconds", { s: took })
					}),
					turn.toolCalls > 0 && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.turnMeta,
						children: t("turn.tools", { n: turn.toolCalls })
					}),
					(turn.tokens ?? 0) > 0 && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.turnMeta,
						children: t("usage.turn", { t: compact(turn.tokens ?? 0) })
					}),
					turn.failures > 0 && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.tlTookFailed,
						children: t("turn.failed", { n: turn.failures })
					})
				]
			})]
		}), !open ? null : entries.length === 0 ? /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("tr", { children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("td", {
			className: styles.eventCell,
			"aria-hidden": "true"
		}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("td", {
			className: styles.contentCell,
			children: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: styles.none,
				children: turn.toolCalls > 0 ? t("turn.windowOnly") : t("turn.empty")
			})
		})] }) : groupByStep(entries).map((group, index) => /* @__PURE__ */ (0, react_jsx_runtime.jsxs)(react.Fragment, { children: [group.step !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("tr", {
			className: styles.stepRow,
			children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("td", {
				className: styles.eventCell,
				"aria-hidden": "true"
			}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("td", {
				className: styles.contentCell,
				children: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
					className: styles.stepLabel,
					children: t("turn.stepN", { n: group.step })
				})
			})]
		}), group.rows.map((entry) => /* @__PURE__ */ (0, react_jsx_runtime.jsx)(ToolRow, {
			entry,
			now,
			showClock,
			turnStart: turn.startedAt,
			expanded: expandedId === "__all__" || expandedId === entry.id,
			selected: picked,
			dim: dimmed,
			onToggle: () => onToggle(entry.id),
			t
		}, entry.id))] }, `${group.step ?? "none"}-${index}`))]
	});
}
/**
* The row detail as a right-hand drawer, the way the trajectory view shows one.
*
* Tabs, a 42px header and a scrolling body — an inline block under the row pushed
* every later row down and could not be compared side by side with the row it
* described.
*/
function DetailDrawer({ entry, now, onClose, t }) {
	const [tab, setTab] = (0, react.useState)("overview");
	const running = entry.status === "running";
	const failed = entry.status === "failed";
	const kind = entry.kind === "tool" ? t("timeline.tool") : entry.kind === "user" ? t("timeline.user") : entry.kind === "context" ? t("lane.context") : t("timeline.assistant");
	const tabs = [
		{
			id: "overview",
			label: t("detail.overview"),
			body: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("dl", {
				className: styles.detailGrid,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("detail.name") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", { children: entry.kind === "tool" ? entry.title : kind }),
					(entry.entryId ?? null) !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsxs)(react_jsx_runtime.Fragment, { children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("detail.entryId") }), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", {
						className: styles.detailMono,
						children: entry.entryId
					})] }),
					entry.kind === "tool" && /* @__PURE__ */ (0, react_jsx_runtime.jsxs)(react_jsx_runtime.Fragment, { children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("overview.status") }), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", { children: running ? t("status.running") : failed ? t("status.failed") : t("status.ok") })] }),
					entry.turn !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsxs)(react_jsx_runtime.Fragment, { children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("overview.at") }), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", { children: entry.step === null ? `#${entry.turn}` : t("overview.atValue", {
						turn: entry.turn,
						step: entry.step
					}) })] })
				]
			})
		},
		{
			id: "args",
			label: t("turn.args"),
			body: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("pre", {
				className: styles.detailPre,
				children: entry.argsFull ?? entry.detail ?? t("detail.none")
			})
		},
		{
			id: "result",
			label: t("turn.result"),
			body: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("pre", {
				className: styles.detailPre,
				children: entry.resultFull ?? entry.result ?? t("detail.none")
			})
		},
		{
			id: "schema",
			label: t("detail.schema"),
			body: /* @__PURE__ */ (0, react_jsx_runtime.jsx)("p", {
				className: styles.none,
				children: t("detail.schemaUnavailable")
			})
		},
		{
			id: "timing",
			label: t("detail.timing"),
			body: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("dl", {
				className: styles.detailGrid,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("timing.started") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", {
						className: styles.detailMono,
						children: stampOf(entry.startedAt)
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("timing.duration") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("dd", { children: [
						millisBetween(entry.startedAt, entry.endedAt ?? now),
						" ",
						t("timing.ms")
					] }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("timing.ended") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", {
						className: styles.detailMono,
						children: entry.endedAt === null ? t("status.running") : stampOf(entry.endedAt)
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dt", { children: t("timing.source") }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("dd", { children: t("timing.sourceSession") })
				]
			})
		}
	];
	const active = tabs.find((item) => item.id === tab) ?? tabs[0];
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("aside", {
		className: styles.details,
		children: [
			/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("header", {
				className: styles.detailsHeader,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("span", {
						className: styles.detailsTitle,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.kindTag,
							"data-kind": entry.kind,
							"data-failed": failed,
							children: kind
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("strong", {
							className: styles.detailsName,
							children: entry.kind === "tool" ? entry.title : kind
						})]
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.detailsLocation,
						children: entry.entryId ?? ""
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
						type: "button",
						className: styles.detailsClose,
						onClick: onClose,
						"aria-label": t("detail.close"),
						children: "×"
					})
				]
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
				className: styles.detailTabs,
				role: "tablist",
				children: tabs.map((item) => /* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
					type: "button",
					role: "tab",
					"aria-selected": item.id === tab,
					className: item.id === tab ? styles.detailTabActive : styles.detailTab,
					onClick: () => setTab(item.id),
					children: item.label
				}, item.id))
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
				className: styles.detailBody,
				children: active?.body
			})
		]
	});
}
/**
* Render the live task view for the current session.
* @param props - projection hook and translator from the slot kit.
* @returns the view body, or an explicit empty state.
*/
function LiveTasksView({ useProjection, t }) {
	const projected = useProjection("liveTask");
	/**
	* Tolerate a host running an older build than this bundle.
	*
	* The browser half and the host half are versioned separately: a page refresh
	* can pair a newer client with the host that is still running, and reading a
	* field the host does not send threw — React then unmounted the view and the
	* panel went blank. Missing fields fall back here, so the worst case is a
	* missing line instead of an empty page. `--stale-host` in
	* `scripts/panel-preview.mjs` renders exactly that pairing.
	*/
	const state = projected === void 0 ? void 0 : {
		...projected,
		turnsTotal: projected.turnsTotal ?? projected.turns.length,
		usage: projected.usage ?? {
			reported: 0,
			input: 0,
			output: 0,
			cacheRead: 0,
			reasoning: 0,
			total: 0
		},
		spans: projected.spans ?? []
	};
	const [selected, setSelected] = (0, react.useState)(null);
	const [expanded, setExpanded] = (0, react.useState)(null);
	const [expandAll, setExpandAll] = (0, react.useState)(false);
	const [failedOnly, setFailedOnly] = (0, react.useState)(false);
	const [query, setQuery] = (0, react.useState)("");
	const [showClock, setShowClock] = (0, react.useState)(true);
	const [turnsOpen, setTurnsOpen] = (0, react.useState)(true);
	const [range, setRange] = (0, react.useState)(null);
	const now = useNow();
	if (state === void 0 || !hasLiveActivity(state)) return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
		className: styles.empty,
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.StateDot, { state: "idle" }), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: t("view.empty") })]
	});
	const inFlight = state.openTools.length > 0;
	const settled = state.endedReason !== null && !state.running;
	const phase = inFlight ? t("phase.tool") : state.running ? t("phase.running") : settled ? t("phase.ended") : t("phase.idle");
	const distinctTools = new Set(state.actions.map((action) => action.name)).size;
	const lastDataAt = Math.max(state.updatedAt ?? 0, state.streamedAt ?? 0);
	const silentSeconds = lastDataAt === 0 ? 0 : secondsBetween(lastDataAt, now);
	const selectedTurn = state.turns.at(-1)?.turn ?? null;
	const shownTurn = selected ?? selectedTurn;
	const pickedTurn = selected;
	const needle = query.trim().toLowerCase();
	const entriesOfTurn = (turn) => state.timeline.filter((entry) => entry.turn === turn && entry.kind !== "turn").filter((entry) => !failedOnly || entry.status === "failed").filter((entry) => needle === "" || entry.title.toLowerCase().includes(needle) || (entry.detail ?? "").toLowerCase().includes(needle) || (entry.result ?? "").toLowerCase().includes(needle)).filter((entry) => range === null || (entry.endedAt ?? entry.startedAt) >= range.from && entry.startedAt <= range.to);
	const detailEntry = expandAll ? null : state.timeline.find((entry) => entry.id === expanded) ?? null;
	return /* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
		className: styles.view,
		children: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
			className: styles.panes,
			children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
				className: styles.paneMain,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("header", {
						className: styles.head,
						children: [
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.StateDot, { state: inFlight || state.running ? "ongoing" : settled ? "done" : "idle" }),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Tag, {
								tone: settled ? "success" : "info",
								children: phase
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
								className: styles.elapsed,
								children: state.running ? t("time.seconds", { s: secondsBetween(state.updatedAt ?? now, now) }) : ""
							})
						]
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("p", {
						className: styles.toolLine,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.toolLineLabel,
							children: inFlight ? t("head.toolRunning") : t("head.toolLast")
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.toolLineValue,
							children: inFlight ? state.openTools.map((call) => call.name).join(", ") : state.actions.at(-1)?.name ?? t("head.toolNone")
						})]
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("p", {
						className: styles.summaryLine,
						children: t("axis.summary", {
							turns: state.turnsTotal,
							calls: state.toolCallsTotal,
							failures: state.failuresTotal,
							tools: state.toolsAvailable ?? "—",
							used: distinctTools
						})
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("p", {
						className: styles.usageLine,
						children: state.usage.reported === 0 ? t("usage.unknown") : t("usage.line", {
							total: compact(state.usage.total),
							input: compact(state.usage.input),
							output: compact(state.usage.output),
							cache: compact(state.usage.cacheRead),
							pct: state.usage.cacheRead + state.usage.input === 0 ? 0 : Math.round(state.usage.cacheRead / (state.usage.cacheRead + state.usage.input) * 100)
						})
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
						className: styles.bar,
						children: [
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("input", {
								className: styles.search,
								type: "search",
								value: query,
								placeholder: t("bar.search"),
								onChange: (event) => setQuery(event.target.value)
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
								type: "button",
								className: failedOnly ? styles.barOn : styles.barButton,
								onClick: () => setFailedOnly(!failedOnly),
								children: t("bar.failedOnly")
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
								type: "button",
								className: styles.barButton,
								onClick: () => {
									setExpanded(null);
									setExpandAll(!expandAll);
								},
								children: expandAll ? t("bar.collapseAll") : t("bar.expandAll")
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
								type: "button",
								className: showClock ? styles.barOn : styles.barButton,
								onClick: () => setShowClock(!showClock),
								children: showClock ? t("bar.clock") : t("bar.duration")
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
								type: "button",
								className: styles.barButton,
								onClick: () => setTurnsOpen(!turnsOpen),
								children: turnsOpen ? t("bar.collapseTurns") : t("bar.expandTurns")
							}),
							range !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)("button", {
								type: "button",
								className: styles.barOn,
								onClick: () => setRange(null),
								children: t("bar.clearRange")
							})
						]
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("section", {
						className: styles.section,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("h4", {
							className: styles.sectionTitle,
							children: state.turnsTotal > state.turns.length ? t("axis.titleWindow", {
								total: state.turnsTotal,
								shown: state.turns.length
							}) : t("axis.title")
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)(LaneChart, {
							spans: state.spans,
							turns: state.turns,
							now,
							selected: shownTurn,
							range,
							t,
							onSelect: setSelected,
							onRange: setRange
						})]
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("section", {
						className: styles.section,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("h4", {
							className: styles.sectionTitle,
							children: t("timeline.title")
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("div", {
							className: styles.tablePane,
							children: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("table", {
								className: styles.table,
								children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("colgroup", { children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("col", { className: styles.eventColumn }), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("col", { className: styles.contentColumn })] }), [...state.turns].reverse().map((turn) => /* @__PURE__ */ (0, react_jsx_runtime.jsx)(TurnSection, {
									turn,
									entries: entriesOfTurn(turn.turn),
									picked: pickedTurn !== null && turn.turn === pickedTurn,
									now,
									showClock,
									open: turnsOpen,
									expandedId: expandAll ? "__all__" : expanded,
									dimmed: pickedTurn !== null && turn.turn !== pickedTurn,
									onToggle: (id) => {
										setExpandAll(false);
										setExpanded(expanded === id ? null : id);
									},
									t
								}, turn.turn))]
							})
						})]
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("section", {
						className: styles.section,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("h4", {
							className: styles.sectionTitle,
							children: t("health.title")
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
							className: styles.health,
							children: [
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: `${t("health.folded")} ${state.health.folded}` }),
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: `${t("health.ignored")} ${state.health.ignored}` }),
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
									className: state.health.unknown > 0 ? styles.healthStale : void 0,
									children: `${t("health.unknown")} ${state.health.unknown}`
								}),
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: `${t("health.frames")} ${state.health.frames}` }),
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
									className: state.health.registry < 0 ? styles.healthStale : void 0,
									children: `${t("health.agents")} ${state.health.agents} / ${t("health.registry")} ${state.health.registry < 0 ? t("health.unreachable") : state.health.registry}`
								}),
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: t("health.deltasValue", {
									ok: state.health.deltasAccepted,
									dropped: state.health.deltasDropped
								}) }),
								/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
									className: silentSeconds > 60 && state.running ? styles.healthStale : void 0,
									children: silentSeconds > 60 && state.running ? t("health.stale", { s: silentSeconds }) : `${t("health.lastData")} ${t("health.silence", { s: silentSeconds })}`
								})
							]
						})]
					})
				]
			}), detailEntry !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)(DetailDrawer, {
				entry: detailEntry,
				now,
				onClose: () => setExpanded(null),
				t
			})]
		})
	});
}
//#endregion
//#region src/client/locales.ts
/**
* Dictionaries of the `liveTasks` namespace.
*
* The panel is organised as modules — an overview, what is running, what it did,
* what just happened — and the keys mirror that structure (`overview.*`,
* `running.*`, `log.*`, `recent.*`) so copy can be read against the layout.
*
* Simplified Chinese is the key-set source of truth; English is typed as
* `Record<LiveTaskKey, string>`, so a missing or extra key is a compile error in
* either direction. Tool names and event types are deliberately left
* untranslated: they are protocol identifiers, and paraphrasing them would hide
* which tool actually ran.
*/
/** Dictionary namespace owned by this plugin. */
const NS = "liveTasks";
/** Simplified Chinese dictionary (the key-set source of truth). */
const zh = {
	"view.tab": "活动",
	"view.empty": "本会话还没有动作。",
	"head.toolRunning": "正在用的工具",
	"head.toolLast": "最近用的工具",
	"head.toolNone": "还没有用过工具",
	"bar.search": "搜索工具或命令",
	"bar.expandAll": "展开全部",
	"bar.collapseAll": "收起全部",
	"bar.failedOnly": "只看失败",
	"bar.scrollHint": "横向可滚动",
	"detail.none": "（没有可显示的内容）",
	"detail.content": "内容",
	"detail.timing": "计时",
	"detail.close": "关闭详情",
	"timing.ended": "结束时间",
	"turn.windowOnly": "更早的明细未保留（仅保留最近 20 行）",
	"detail.schema": "Schema",
	"detail.schemaUnavailable": "Schema 不可用",
	"timing.ms": "毫秒",
	"timing.source": "计时来源",
	"timing.sourceSession": "会话时间戳",
	"timeline.toolCallsOnly": "（仅工具调用）",
	"detail.name": "名称",
	"detail.entryId": "插件 ID",
	"usage.line": "本会话 {total} tok · 输入 {input} · 输出 {output} · 缓存读取 {cache}（{pct}%）",
	"usage.unknown": "本会话还没有用量报告",
	"usage.turn": "{t} tok",
	"axis.title": "轮次横轴（时间向右）",
	"axis.titleWindow": "轮次横轴（最近 {shown} 轮，共 {total} 轮）",
	"axis.turn": "第 {n} 轮",
	"axis.summary": "本会话 {turns} 轮 · {calls} 次调用 · 失败 {failures} · 可用工具 {tools}（用到 {used} 种）",
	"turn.stepN": "第 {n} 步",
	"detail.overview": "概述",
	"timing.duration": "时长",
	"timing.started": "开始时间",
	"turn.tools": "{n} 个工具",
	"turn.failed": "{n} 次失败",
	"turn.expand": "点击查看详情",
	"turn.args": "参数",
	"turn.result": "结果",
	"turn.empty": "这一轮没有工具调用",
	"lane.input": "输入",
	"lane.model": "模型",
	"lane.tools": "工具",
	"lane.you": "你",
	"lane.context": "上下文",
	"bar.duration": "时长",
	"bar.clock": "实际时间",
	"bar.collapseTurns": "收起轮次",
	"bar.clearRange": "清除选择",
	"bar.rangeHint": "在时间图上拖动可框选",
	"bar.expandTurns": "展开轮次",
	"timeline.title": "时间线",
	"timeline.user": "你",
	"timeline.assistant": "模型",
	"timeline.tool": "工具",
	"timeline.turnN": "第 {n} 轮",
	"overview.title": "概览",
	"overview.status": "状态",
	"overview.at": "位置",
	"overview.elapsed": "已运行",
	"overview.callsTurn": "本轮调用（回合）",
	"overview.callsTotal": "累计调用（会话）",
	"overview.failures": "失败（会话）",
	"overview.tools": "可用工具",
	"overview.toolsUsed": "已用到 {n} 种",
	"overview.atValue": "#{turn} · 第 {step} 步",
	"overview.turnOnly": "#{turn}",
	"running.title": "正在跑",
	"running.empty": "现在没有在跑的动作",
	"running.started": "已跑 {s} 秒",
	"log.title": "动作日志（本会话最近 8 次）",
	"log.filterAll": "最近 {n} 次",
	"log.filterFailed": "只看失败 {n}",
	"log.filterEmpty": "没有符合条件的记录",
	"log.time": "时间",
	"log.tool": "工具",
	"log.did": "干了什么",
	"log.took": "耗时",
	"log.result": "结果",
	"recent.title": "最近动静",
	"health.title": "运行状况",
	"health.folded": "已折叠事件",
	"health.ignored": "已忽略（会话管理类）",
	"health.unknown": "未知类型",
	"health.frames": "收到流式帧",
	"health.agents": "已接管 agent",
	"health.registry": "注册表可见",
	"health.unreachable": "不可达",
	"health.deltas": "流式增量",
	"health.deltasValue": "接受 {ok} · 丢弃 {dropped}",
	"health.lastData": "数据更新",
	"health.silence": "{s} 秒前",
	"health.stale": "已 {s} 秒没有新数据",
	"status.ok": "完成",
	"status.failed": "失败",
	"status.running": "进行中",
	"phase.running": "正在干活",
	"phase.tool": "等工具返回",
	"phase.idle": "空闲",
	"phase.ended": "已结束",
	"time.seconds": "{s} 秒",
	"time.justNow": "刚刚",
	"time.agoSeconds": "{s} 秒前",
	"time.agoMinutes": "{m} 分前",
	"event.turnStart": "开始处理",
	"event.turnEnd": "处理结束",
	"event.userMessage": "收到你的消息",
	"event.assistantMessage": "模型回复",
	"event.toolCall": "调用 {name}",
	"event.toolResult": "{name} 返回"
};
/** English dictionary, key-identical to the Chinese source of truth. */
const en = {
	"view.tab": "Activity",
	"view.empty": "This session has no actions yet.",
	"head.toolRunning": "Tool in use",
	"head.toolLast": "Last tool used",
	"head.toolNone": "No tool used yet",
	"bar.search": "Filter by tool or command",
	"bar.expandAll": "Expand all",
	"bar.collapseAll": "Collapse all",
	"bar.failedOnly": "Failures only",
	"bar.scrollHint": "scrolls sideways",
	"detail.none": "(nothing to show)",
	"detail.content": "Content",
	"detail.schema": "Schema",
	"detail.schemaUnavailable": "Schema unavailable",
	"timing.ms": "ms",
	"timing.source": "Timing source",
	"timing.sourceSession": "session timestamp",
	"timeline.toolCallsOnly": "(tool calls only)",
	"detail.name": "Name",
	"detail.entryId": "Plugin id",
	"detail.timing": "Timing",
	"detail.close": "Close details",
	"timing.ended": "Ended",
	"turn.windowOnly": "Earlier detail not retained (last 20 rows kept)",
	"usage.line": "{total} tok this session · in {input} · out {output} · cache read {cache} ({pct}%)",
	"usage.unknown": "No usage reported yet",
	"usage.turn": "{t} tok",
	"axis.title": "Turns as time (left to right)",
	"axis.titleWindow": "Turns as time (last {shown} of {total})",
	"axis.turn": "turn {n}",
	"axis.summary": "{turns} turns · {calls} calls · {failures} failed · {tools} tools offered ({used} used)",
	"turn.stepN": "step {n}",
	"detail.overview": "Summary",
	"timing.duration": "Duration",
	"timing.started": "Started",
	"turn.tools": "{n} tools",
	"turn.failed": "{n} failed",
	"turn.expand": "click for details",
	"turn.args": "arguments",
	"turn.result": "result",
	"turn.empty": "no tool calls in this turn",
	"lane.input": "input",
	"lane.model": "model",
	"lane.tools": "tools",
	"lane.you": "you",
	"lane.context": "context",
	"bar.duration": "duration",
	"bar.clock": "wall clock",
	"bar.collapseTurns": "Collapse turns",
	"bar.clearRange": "Clear selection",
	"bar.rangeHint": "drag on the chart to select",
	"bar.expandTurns": "Expand turns",
	"timeline.title": "Timeline",
	"timeline.user": "you",
	"timeline.assistant": "model",
	"timeline.tool": "tool",
	"timeline.turnN": "turn {n}",
	"overview.title": "Overview",
	"overview.status": "State",
	"overview.at": "Position",
	"overview.elapsed": "Elapsed",
	"overview.callsTurn": "Calls (this turn)",
	"overview.callsTotal": "Calls (session)",
	"overview.failures": "Failures (session)",
	"overview.tools": "Tools offered",
	"overview.toolsUsed": "{n} used",
	"overview.atValue": "#{turn} · step {step}",
	"overview.turnOnly": "#{turn}",
	"running.title": "Running now",
	"running.empty": "Nothing is running right now",
	"running.started": "{s}s so far",
	"log.title": "Activity log (last 8 this session)",
	"log.filterAll": "Last {n}",
	"log.filterFailed": "Failures only {n}",
	"log.filterEmpty": "No record matches this filter",
	"log.time": "time",
	"log.tool": "tool",
	"log.did": "what it did",
	"log.took": "took",
	"log.result": "result",
	"recent.title": "Just happened",
	"health.title": "Panel health",
	"health.folded": "Events folded",
	"health.ignored": "Ignored (session setup)",
	"health.unknown": "Unknown types",
	"health.frames": "Stream frames",
	"health.agents": "Agents attached",
	"health.registry": "Registry size",
	"health.unreachable": "unreachable",
	"health.deltas": "Stream deltas",
	"health.deltasValue": "{ok} kept · {dropped} dropped",
	"health.lastData": "Last data",
	"health.silence": "{s}s ago",
	"health.stale": "no new data for {s}s",
	"status.ok": "done",
	"status.failed": "failed",
	"status.running": "running",
	"phase.running": "working",
	"phase.tool": "waiting for a tool",
	"phase.idle": "idle",
	"phase.ended": "finished",
	"time.seconds": "{s}s",
	"time.justNow": "just now",
	"time.agoSeconds": "{s}s ago",
	"time.agoMinutes": "{m}m ago",
	"event.turnStart": "started working",
	"event.turnEnd": "finished working",
	"event.userMessage": "your message arrived",
	"event.assistantMessage": "model replied",
	"event.toolCall": "called {name}",
	"event.toolResult": "{name} returned"
};
//#endregion
//#region src/client/index.ts
/**
* Client services this half needs ready before it activates.
*
* `slots` and `locale` are the two it calls directly. `sessions` and
* `uiConversation` are what the standard slot kit is assembled from: the kit
* hands the component `useProjection`, which reads the session-projection
* mirror, and the header slot itself belongs to the conversation surface. The
* official client halves that read a projection declare the same two (see
* `dsh-client-ui-goal`), and without them the kit cannot supply the hook.
*/
const inject = [
	"slots",
	"locale",
	"sessions",
	"uiConversation"
];
/**
* Client plugin body: register the dictionaries and the header action.
* @param ctx - client root context.
*/
function apply(ctx) {
	const t = ctx.locale.bind(NS);
	ctx.effect(() => ctx.locale.register(NS, {
		zh,
		en
	}), "ui-live-tasks: dictionaries");
	ctx.slots.inject("conversation.view", () => ctx.slots.register({
		name: "conversation.view",
		id: "live-tasks",
		order: 20,
		label: () => t("view.tab"),
		locale: NS
	}, LiveTasksView));
	ctx.slots.inject("conversation.session.header.actions", () => ctx.slots.register({
		name: "conversation.session.header.actions",
		id: "live-tasks",
		order: 30,
		locale: NS
	}, LiveTasksHeaderAction));
}
//#endregion
exports.apply = apply;
exports.inject = inject;
		return module.exports;
	}
});
