// Generated by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
	id: "soia-dsh-client-ui-live-tasks",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
let _deepseek_ai_dsh_client_ui_primitives = require("@deepseek-ai/dsh-client-ui-primitives");
let react = require("react");
let react_jsx_runtime = require("react/jsx-runtime");
//#region src/shared/live-task-state.ts
/** One frozen array reused for every state without open tool calls. */
const NO_EVENTS = Object.freeze([]);
const NO_TOOLS = Object.freeze([]);
Object.freeze({
	turn: null,
	step: null,
	running: false,
	seq: 0,
	updatedAt: null,
	lastTool: null,
	openTools: NO_TOOLS,
	toolCallsInTurn: 0,
	streamedTextLength: 0,
	streamedAt: null,
	lastEvent: null,
	recent: NO_EVENTS,
	endedReason: null
});
/**
* Whether the session has shown anything at all.
*
* A surface that renders only when there is something to say uses this to stay
* completely absent for a session that never produced an event.
* @param state - current state.
* @returns true once any observation, durable or transient, has been folded.
*/
function hasLiveActivity(state) {
	return state.updatedAt !== null;
}
//#endregion
//#region src/client/styles.ts
/**
* Layout skeleton for the live-task view.
*
* Buttons, pills, tags and state dots come from the official primitives; what
* is left here is only the layout they deliberately do not own — the row grid
* and the view padding. Class names carry an `lt-` prefix so they cannot
* collide with the page's own generic names, and the stylesheet is injected
* once per document, tagged with the plugin id.
*
* The `--dsw-*` variables come from the host shell, so the view follows the
* active theme without duplicating any palette.
*/
const CSS = `
.lt-view { display: flex; flex-direction: column; gap: 16px; padding: 18px 20px; }
.lt-head { display: flex; align-items: center; gap: 8px; }
.lt-title { font-size: 13.5px; font-weight: 600; color: var(--dsw-alias-label-primary); }
.lt-elapsed { margin-left: auto; color: var(--dsw-alias-label-tertiary); font-size: 12px; }
.lt-section { display: flex; flex-direction: column; gap: 6px; }
.lt-sectionTitle { margin: 0; font-size: 12px; font-weight: 600; letter-spacing: .02em;
  color: var(--dsw-alias-label-tertiary); }
.lt-list { display: flex; flex-direction: column; gap: 2px; margin: 0; padding: 0; list-style: none; }
.lt-call { display: grid; grid-template-columns: 10px 84px 1fr; align-items: center; gap: 8px;
  padding: 6px 8px; border-radius: 8px; font-size: 13px; line-height: 18px;
  background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 4%)); }
.lt-callName { color: var(--dsw-alias-label-primary); font-weight: 600; }
.lt-callDetail { min-width: 0; overflow: hidden; font-family: var(--dsw-font-mono, monospace);
  white-space: nowrap; text-overflow: ellipsis; color: var(--dsw-alias-label-secondary); }
.lt-event { display: grid; grid-template-columns: 76px 112px 1fr; align-items: baseline; gap: 10px;
  padding: 4px 8px; border-radius: 6px; font-size: 12.5px; line-height: 18px; }
.lt-event:nth-child(odd) { background: var(--dsw-alias-bg-base-secondary, rgb(0 0 0 / 3%)); }
.lt-eventTime { color: var(--dsw-alias-label-tertiary); }
.lt-eventType { color: var(--dsw-alias-label-secondary); font-family: var(--dsw-font-mono, monospace); }
.lt-eventDetail { min-width: 0; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;
  color: var(--dsw-alias-label-primary); font-family: var(--dsw-font-mono, monospace); }
.lt-none { margin: 0; color: var(--dsw-alias-label-tertiary); font-size: 12.5px; }
.lt-rows { display: flex; flex-direction: column; gap: 2px; }
.lt-row { display: grid; grid-template-columns: 132px 1fr; align-items: baseline; gap: 12px;
  padding: 6px 8px; border-radius: 8px; font-size: 13px; line-height: 18px;
  color: var(--dsw-alias-label-primary); }
.lt-rowLabel { color: var(--dsw-alias-label-tertiary); }
.lt-rowValue { min-width: 0; overflow: hidden; font-family: var(--dsw-font-mono, monospace);
  white-space: nowrap; text-overflow: ellipsis; }
.lt-empty { display: flex; align-items: center; gap: 8px; padding: 24px 20px;
  color: var(--dsw-alias-label-tertiary); font-size: 13px; }
`;
/** Class names this view applies. */
const styles = {
	view: "lt-view",
	head: "lt-head",
	title: "lt-title",
	elapsed: "lt-elapsed",
	section: "lt-section",
	sectionTitle: "lt-sectionTitle",
	list: "lt-list",
	call: "lt-call",
	callName: "lt-callName",
	callDetail: "lt-callDetail",
	event: "lt-event",
	eventTime: "lt-eventTime",
	eventType: "lt-eventType",
	eventDetail: "lt-eventDetail",
	none: "lt-none",
	rows: "lt-rows",
	row: "lt-row",
	rowLabel: "lt-rowLabel",
	rowValue: "lt-rowValue",
	empty: "lt-empty"
};
/** Plugin id the injected style tag is tagged with. */
const STYLE_TAG_ID = "ui-live-tasks";
if (typeof document !== "undefined" && document.querySelector(`style[data-plugin-css="${STYLE_TAG_ID}"]`) === null) {
	const tag = document.createElement("style");
	tag.dataset.plugin = STYLE_TAG_ID;
	tag.dataset.pluginCss = STYLE_TAG_ID;
	tag.textContent = CSS;
	document.head.append(tag);
}
//#endregion
//#region src/client/LiveTasksView.tsx
/**
* The `conversation.view` entry: what this session's task is doing right now.
*
* The first version showed counts, which answered "is anything running" but not
* "what is it doing". This one shows the in-flight calls with the argument line
* the host folded for each, a trailing window of recent events with relative
* times, and how long the turn has been running — the three things a reader
* actually needs to tell a working session from a stuck one.
*
* Visuals come from the official primitives (`StateDot`, `Tag`, `Pill`) so the
* view sits in the same design system as the built-in views; the local
* stylesheet is only the layout skeleton primitives do not provide.
*
* @module soia-dsh-client-ui-live-tasks/client/view
*/
/**
* Re-render once a second so elapsed and relative times stay true.
* @returns the current epoch milliseconds.
*/
function useNow() {
	const [now, setNow] = (0, react.useState)(() => Date.now());
	(0, react.useEffect)(() => {
		const timer = setInterval(() => setNow(Date.now()), 1e3);
		return () => clearInterval(timer);
	}, []);
	return now;
}
/** Render a duration in seconds as "just now" / "Ns ago" / "Nm ago". */
function ago(at, now, t) {
	const seconds = Math.max(0, Math.round((now - at) / 1e3));
	if (seconds < 2) return t("time.justNow");
	if (seconds < 60) return t("time.agoSeconds", { s: seconds });
	return t("time.agoMinutes", { m: Math.round(seconds / 60) });
}
/** One event line in the trail. */
function EventRow({ summary, now, t }) {
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("li", {
		className: styles.event,
		children: [
			/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: styles.eventTime,
				children: ago(summary.time, now, t)
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: styles.eventType,
				children: summary.type
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: styles.eventDetail,
				children: summary.detail ?? ""
			})
		]
	});
}
/**
* Render the live task view for the current session.
* @param props - projection hook and translator from the slot kit.
* @returns the view body, or an explicit empty state.
*/
function LiveTasksView({ useProjection, t }) {
	const state = useProjection("liveTask");
	const now = useNow();
	if (state === void 0 || !hasLiveActivity(state)) return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
		className: styles.empty,
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.StateDot, { state: "idle" }), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", { children: t("view.empty") })]
	});
	const inFlight = state.openTools.length > 0;
	const phase = inFlight ? t("phase.tool") : state.running ? t("phase.running") : state.endedReason !== null ? t("phase.ended") : t("phase.idle");
	const settled = state.endedReason !== null && !state.running;
	const elapsedSeconds = state.updatedAt === null ? 0 : Math.round((now - state.updatedAt) / 1e3);
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
		className: styles.view,
		children: [
			/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("header", {
				className: styles.head,
				children: [
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.StateDot, { state: inFlight || state.running ? "ongoing" : settled ? "done" : "idle" }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("strong", {
						className: styles.title,
						children: t("view.title")
					}),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Tag, {
						tone: settled ? "success" : "info",
						children: phase
					}),
					state.turn !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Pill, { children: `#${state.turn} · ${t("row.step")} ${state.step ?? "—"}` }),
					/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
						className: styles.elapsed,
						children: state.running ? t("time.runningFor", { s: elapsedSeconds }) : ago(state.updatedAt ?? now, now, t)
					})
				]
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("section", {
				className: styles.section,
				children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("h4", {
					className: styles.sectionTitle,
					children: t("section.running")
				}), state.openTools.length === 0 ? /* @__PURE__ */ (0, react_jsx_runtime.jsx)("p", {
					className: styles.none,
					children: t("tool.none")
				}) : /* @__PURE__ */ (0, react_jsx_runtime.jsx)("ul", {
					className: styles.list,
					children: state.openTools.map((call) => /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("li", {
						className: styles.call,
						children: [
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.StateDot, {
								state: "ongoing",
								size: 8
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
								className: styles.callName,
								children: call.name
							}),
							/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
								className: styles.callDetail,
								children: call.detail ?? ""
							})
						]
					}, call.callId))
				})]
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("section", {
				className: styles.section,
				children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("h4", {
					className: styles.sectionTitle,
					children: t("section.recent")
				}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("ul", {
					className: styles.list,
					children: [...state.recent].reverse().map((summary) => /* @__PURE__ */ (0, react_jsx_runtime.jsx)(EventRow, {
						summary,
						now,
						t
					}, `${summary.seq}-${summary.type}`))
				})]
			}),
			/* @__PURE__ */ (0, react_jsx_runtime.jsx)("section", {
				className: styles.section,
				children: /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
					className: styles.rows,
					children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
						className: styles.row,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.rowLabel,
							children: t("row.toolCalls")
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.rowValue,
							children: String(state.toolCallsInTurn)
						})]
					}), state.lastTool !== null && /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
						className: styles.row,
						children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.rowLabel,
							children: t("row.lastTool")
						}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
							className: styles.rowValue,
							children: `${state.lastTool.name} · ${state.lastTool.open ? t("tool.open") : state.lastTool.failed === true ? t("tool.failed") : t("tool.done")}`
						})]
					})]
				})
			})
		]
	});
}
//#endregion
//#region src/client/locales.ts
/**
* Dictionaries of the `liveTasks` namespace.
*
* Simplified Chinese is the key-set source of truth; English carries the
* identical key set, so neither direction can leave a key unresolved. Only
* human-facing panel copy lives here — the package adds nothing model-visible,
* and a protocol token such as a tool name or a `TurnEndReason.kind` is
* rendered verbatim rather than translated.
*/
/** Dictionary namespace owned by this plugin. */
const NS = "liveTasks";
/** Simplified Chinese dictionary (the key-set source of truth). */
const zh = {
	"section.running": "正在跑",
	"section.recent": "最近事件",
	"tool.none": "当前没有在跑的调用",
	"time.runningFor": "已运行 {s} 秒",
	"time.agoSeconds": "{s} 秒前",
	"time.agoMinutes": "{m} 分前",
	"time.justNow": "刚刚",
	"view.tab": "任务",
	"view.title": "会话任务状态",
	"view.empty": "本会话当前没有进行中的任务。",
	"panel.empty": "本次会话还没有事件。",
	"row.phase": "状态",
	"row.turn": "回合",
	"row.step": "步骤",
	"row.lastTool": "最后工具调用",
	"row.toolCalls": "本轮工具调用数",
	"row.lastEvent": "最后事件",
	"row.endedReason": "结束原因",
	"phase.running": "运行中",
	"phase.tool": "等待工具结果",
	"phase.idle": "空闲",
	"phase.ended": "已结束",
	"tool.open": "进行中",
	"tool.failed": "失败",
	"tool.done": "已完成",
	"value.none": "无",
	"value.openCount": "{count} 个进行中"
};
/** English dictionary, key-identical to the Chinese source of truth. */
const en = {
	"section.running": "In flight",
	"section.recent": "Recent events",
	"tool.none": "No call in flight",
	"time.runningFor": "running for {s}s",
	"time.agoSeconds": "{s}s ago",
	"time.agoMinutes": "{m}m ago",
	"time.justNow": "just now",
	"view.tab": "Tasks",
	"view.title": "Session task state",
	"view.empty": "This session has no task in progress.",
	"panel.empty": "This session has no events yet.",
	"row.phase": "State",
	"row.turn": "Turn",
	"row.step": "Step",
	"row.lastTool": "Last tool call",
	"row.toolCalls": "Tool calls this turn",
	"row.lastEvent": "Last event",
	"row.endedReason": "Ended",
	"phase.running": "running",
	"phase.tool": "waiting for a tool result",
	"phase.idle": "idle",
	"phase.ended": "ended",
	"tool.open": "in flight",
	"tool.failed": "failed",
	"tool.done": "settled",
	"value.none": "none",
	"value.openCount": "{count} in flight"
};
//#endregion
//#region src/client/index.ts
/**
* Client services this half needs ready before it activates.
*
* `slots` and `locale` are the two it calls directly. `sessions` and
* `uiConversation` are what the standard slot kit is assembled from: the kit
* hands the component `useProjection`, which reads the session-projection
* mirror, and the header slot itself belongs to the conversation surface. The
* official client halves that read a projection declare the same two (see
* `dsh-client-ui-goal`), and without them the kit cannot supply the hook.
*/
const inject = [
	"slots",
	"locale",
	"sessions",
	"uiConversation"
];
/**
* Client plugin body: register the dictionaries and the header action.
* @param ctx - client root context.
*/
function apply(ctx) {
	const t = ctx.locale.bind(NS);
	ctx.effect(() => ctx.locale.register(NS, {
		zh,
		en
	}), "ui-live-tasks: dictionaries");
	ctx.slots.inject("conversation.view", () => ctx.slots.register({
		name: "conversation.view",
		id: "live-tasks",
		order: 20,
		label: () => t("view.tab"),
		locale: NS
	}, LiveTasksView));
}
//#endregion
exports.apply = apply;
exports.inject = inject;
		return module.exports;
	}
});
