// Generated by scripts/build-client.mjs — do not edit by hand.
window.__ModuleLoader__.load({
	id: "soia-dsh-client-ui-live-tasks",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
let react = require("react");
let react_jsx_runtime = require("react/jsx-runtime");
//#region src/shared/live-task-state.ts
/** One frozen array reused for every state without open tool calls. */
const NO_TOOLS = Object.freeze([]);
Object.freeze({
	turn: null,
	step: null,
	running: false,
	seq: 0,
	updatedAt: null,
	lastTool: null,
	openTools: NO_TOOLS,
	toolCallsInTurn: 0,
	streamedTextLength: 0,
	streamedAt: null,
	lastEvent: null,
	endedReason: null
});
/**
* Whether the session has shown anything at all.
*
* A surface that renders only when there is something to say uses this to stay
* completely absent for a session that never produced an event.
* @param state - current state.
* @returns true once any observation, durable or transient, has been folded.
*/
function hasLiveActivity(state) {
	return state.updatedAt !== null;
}
//#endregion
//#region src/shared/projection.ts
/**
* Projection key of the live-task unit.
*
* A profile-local handle inside the projection table, in the camelCase noun
* shape the official units use (`sessionStats`, `todos`). Renaming it is a wire
* change: the browser half reads the same constant, so both halves move
* together and `tests/host/index.test.ts` pins the pair.
*/
const LIVE_TASK_PROJECTION_KEY = "liveTask";
//#endregion
//#region src/client/styles.ts
/**
* Styles for the session-header action.
*
* Hand-written instead of a CSS-module import on purpose: a browser half is
* bundled into the loader's lazy CommonJS factory, and pulling in a CSS build
* pipeline (lightningcss + a virtual-module plugin) would add a second toolchain
* to this repository for one 96-line stylesheet. Class names carry an `lt-`
* prefix so they cannot collide with the page's own generic names, and the
* stylesheet is injected once per document, tagged with the plugin id so it is
* findable and removable.
*
* The theme variables (`--dsw-*`) come from the host shell; this file only
* consumes them, so the panel follows the active theme without duplicating any
* palette.
*/
const CSS = `.lt-root {
  position: relative;
}

.lt-trigger {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  min-height: 28px;
  padding: 3px 6px;
  color: var(--dsw-alias-label-tertiary);
  font-size: 12px;
  line-height: 18px;
  background: 0 0;
  border: 0;
  border-radius: 6px;
  cursor: pointer;
}

.lt-trigger:hover,
.lt-trigger:focus-visible {
  color: var(--dsw-alias-label-secondary);
}

.lt-dotIdle,
.lt-dotTool {
  flex: none;
  width: 6px;
  height: 6px;
  border-radius: 50%;
}

.lt-dotIdle {
  background: var(--dsw-alias-label-tertiary);
}

.lt-dotTool {
  background: var(--dsw-alias-label-secondary);
}

.lt-label {
  max-width: 18ch;
  overflow: hidden;
  font-family: var(--dsw-font-mono, monospace);
  white-space: nowrap;
  text-overflow: ellipsis;
}

.lt-menu {
  position: absolute;
  top: calc(100% + 5px);
  left: 0;
  z-index: 100;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  gap: 1px;
  width: 336px;
  max-width: min(400px, 100vw - 32px);
  max-height: min(420px, 100vh - 140px);
  margin: 0;
  padding: 4px;
  overflow: auto;
  list-style: none;
  background: var(--dsw-specific-menu);
  border: 0;
  border-radius: 20px;
  box-shadow: var(--dsw-elevation-prominent);
}

.lt-row {
  box-sizing: border-box;
  display: flex;
  align-items: baseline;
  gap: 8px;
  width: 100%;
  min-height: 28px;
  padding: 5px 8px;
  color: var(--dsw-alias-label-primary);
  font-size: 13px;
  line-height: 18px;
  border-radius: 8px;
}

.lt-rowLabel {
  flex: none;
  color: var(--dsw-alias-label-tertiary);
}

.lt-rowValue {
  min-width: 0;
  overflow: hidden;
  font-family: var(--dsw-font-mono, monospace);
  white-space: nowrap;
  text-overflow: ellipsis;
}
`;
/** Class names the component applies, prefixed so they stay this plugin's own. */
const styles = {
	root: "lt-root",
	trigger: "lt-trigger",
	dotIdle: "lt-dotIdle",
	dotTool: "lt-dotTool",
	label: "lt-label",
	menu: "lt-menu",
	row: "lt-row",
	rowLabel: "lt-rowLabel",
	rowValue: "lt-rowValue"
};
/** Plugin id the injected style tag is tagged with. */
const STYLE_TAG_ID = "ui-live-tasks";
if (typeof document !== "undefined" && document.querySelector(`style[data-plugin-css="${STYLE_TAG_ID}"]`) === null) {
	const tag = document.createElement("style");
	tag.dataset.plugin = STYLE_TAG_ID;
	tag.dataset.pluginCss = STYLE_TAG_ID;
	tag.textContent = CSS;
	document.head.append(tag);
}
//#endregion
//#region src/client/LiveTasksAction.tsx
/**
* Session-header entry point for the live-task panel.
*
* The component is a pure reader: the host folds the state and the projection
* registry mirrors it, so there is no fetch, no subscription to a private
* channel, and no derived state beyond whether the popover is open. The only
* fact it computes locally is the trigger's own label.
*
* It renders nothing at all until the session projection carries a state with
* activity, so an ordinary conversation never grows a control for a capability
* it is not using.
*/
/**
* One labeled row of the popover.
* @param props - localized label and the value to show beside it.
* @returns the row element.
*/
function Row({ label, value }) {
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("li", {
		className: styles.row,
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
			className: styles.rowLabel,
			children: label
		}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
			className: styles.rowValue,
			children: value
		})]
	});
}
/**
* Short state word for the trigger and the phase row.
* @param state - current projection value.
* @param t - namespace translator.
* @returns the localized phase label.
*/
function phaseLabel(state, t) {
	if (state.openTools.length > 0) return t("phase.tool");
	if (state.running) return t("phase.running");
	if (state.endedReason !== null) return t("phase.ended");
	return t("phase.idle");
}
/**
* Session-header action and popover for this session's task state.
* @param props - runtime slot currency plus the namespace translator.
* @returns the trigger and its popover, or null when there is nothing to show.
*/
function LiveTasksAction({ useProjection, t }) {
	const state = useProjection(LIVE_TASK_PROJECTION_KEY);
	const [open, setOpen] = (0, react.useState)(false);
	const root = (0, react.useRef)(null);
	const trigger = (0, react.useRef)(null);
	(0, react.useEffect)(() => {
		if (!open) return;
		const onKeyDown = (event) => {
			if (event.key !== "Escape") return;
			setOpen(false);
			trigger.current?.focus();
		};
		const onPointerDown = (event) => {
			const target = event.target;
			if (target instanceof Node && root.current?.contains(target) === true) return;
			setOpen(false);
		};
		document.addEventListener("keydown", onKeyDown);
		document.addEventListener("pointerdown", onPointerDown);
		return () => {
			document.removeEventListener("keydown", onKeyDown);
			document.removeEventListener("pointerdown", onPointerDown);
		};
	}, [open]);
	if (state === void 0 || !hasLiveActivity(state)) return null;
	const openTool = state.openTools.at(-1);
	const label = openTool !== void 0 ? openTool.name : state.running ? t("trigger.running") : t("trigger.idle");
	const toolValue = state.lastTool === null ? t("value.none") : [
		state.lastTool.name,
		state.lastTool.open ? t("tool.open") : t("tool.done"),
		...state.lastTool.failed === true ? [t("tool.failed")] : []
	].join(" · ");
	return /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("div", {
		className: styles.root,
		ref: root,
		children: [/* @__PURE__ */ (0, react_jsx_runtime.jsxs)("button", {
			type: "button",
			ref: trigger,
			className: styles.trigger,
			"aria-haspopup": "dialog",
			"aria-expanded": open,
			"aria-label": t("panel.aria"),
			onClick: () => {
				setOpen((wasOpen) => !wasOpen);
			},
			children: [/* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: openTool === void 0 ? styles.dotIdle : styles.dotTool,
				"aria-hidden": "true"
			}), /* @__PURE__ */ (0, react_jsx_runtime.jsx)("span", {
				className: styles.label,
				children: label
			})]
		}), open ? /* @__PURE__ */ (0, react_jsx_runtime.jsxs)("ul", {
			className: styles.menu,
			"aria-label": t("panel.aria"),
			children: [
				/* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.phase"),
					value: phaseLabel(state, t)
				}),
				/* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.turn"),
					value: state.turn === null ? t("value.none") : String(state.turn)
				}),
				/* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.step"),
					value: state.step === null ? t("value.none") : String(state.step)
				}),
				/* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.lastTool"),
					value: toolValue
				}),
				/* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.toolCalls"),
					value: String(state.toolCallsInTurn)
				}),
				/* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.lastEvent"),
					value: state.lastEvent === null ? t("value.none") : state.lastEvent.detail === null ? state.lastEvent.type : `${state.lastEvent.type} · ${state.lastEvent.detail}`
				}),
				state.endedReason === null ? null : /* @__PURE__ */ (0, react_jsx_runtime.jsx)(Row, {
					label: t("row.endedReason"),
					value: state.endedReason
				})
			]
		}) : null]
	});
}
//#endregion
//#region src/client/locales.ts
/**
* Dictionaries of the `liveTasks` namespace.
*
* Simplified Chinese is the key-set source of truth; English carries the
* identical key set, so neither direction can leave a key unresolved. Only
* human-facing panel copy lives here — the package adds nothing model-visible,
* and a protocol token such as a tool name or a `TurnEndReason.kind` is
* rendered verbatim rather than translated.
*/
/** Dictionary namespace owned by this plugin. */
const NS = "liveTasks";
/** Simplified Chinese dictionary (the key-set source of truth). */
const zh = {
	"trigger.running": "运行中",
	"trigger.idle": "空闲",
	"panel.aria": "会话任务状态",
	"panel.empty": "本次会话还没有事件。",
	"row.phase": "状态",
	"row.turn": "回合",
	"row.step": "步骤",
	"row.lastTool": "最后工具调用",
	"row.toolCalls": "本轮工具调用数",
	"row.lastEvent": "最后事件",
	"row.endedReason": "结束原因",
	"phase.running": "运行中",
	"phase.tool": "等待工具结果",
	"phase.idle": "空闲",
	"phase.ended": "已结束",
	"tool.open": "进行中",
	"tool.failed": "失败",
	"tool.done": "已完成",
	"value.none": "无",
	"value.openCount": "{count} 个进行中"
};
/** English dictionary, key-identical to the Chinese source of truth. */
const en = {
	"trigger.running": "running",
	"trigger.idle": "idle",
	"panel.aria": "Session task state",
	"panel.empty": "This session has no events yet.",
	"row.phase": "State",
	"row.turn": "Turn",
	"row.step": "Step",
	"row.lastTool": "Last tool call",
	"row.toolCalls": "Tool calls this turn",
	"row.lastEvent": "Last event",
	"row.endedReason": "Ended",
	"phase.running": "running",
	"phase.tool": "waiting for a tool result",
	"phase.idle": "idle",
	"phase.ended": "ended",
	"tool.open": "in flight",
	"tool.failed": "failed",
	"tool.done": "settled",
	"value.none": "none",
	"value.openCount": "{count} in flight"
};
//#endregion
//#region src/client/index.ts
/**
* Client services this half needs ready before it activates.
*
* `slots` and `locale` are the two it calls directly. `sessions` and
* `uiConversation` are what the standard slot kit is assembled from: the kit
* hands the component `useProjection`, which reads the session-projection
* mirror, and the header slot itself belongs to the conversation surface. The
* official client halves that read a projection declare the same two (see
* `dsh-client-ui-goal`), and without them the kit cannot supply the hook.
*/
const inject = [
	"slots",
	"locale",
	"sessions",
	"uiConversation"
];
/**
* Client plugin body: register the dictionaries and the header action.
* @param ctx - client root context.
*/
function apply(ctx) {
	ctx.effect(() => ctx.locale.register(NS, {
		zh,
		en
	}), "ui-live-tasks: dictionaries");
	ctx.slots.inject("conversation.session.header.actions", () => ctx.slots.register({
		name: "conversation.session.header.actions",
		id: "live-tasks",
		order: 30,
		locale: NS
	}, LiveTasksAction));
}
//#endregion
exports.apply = apply;
exports.inject = inject;
		return module.exports;
	}
});
