#!/usr/bin/env node
/**
 * Build each browser half into the loader artifact the Web shell expects.
 *
 * The official client packages ship a `lib/client.js` in a specific shape: it
 * calls `window.__ModuleLoader__.load({ id, factory })` and the factory is a
 * lazy CommonJS module whose `require` is the loader's module table. The shared
 * preset that produces it lives in the harness monorepo and is not published to
 * npm, so this script reproduces the part a plugin actually needs:
 *
 *  1. bundle `src/client/index.ts` (or `.tsx`) to CommonJS with the host-provided
 *     modules left external — react, the JSX runtime, and every
 *     `@deepseek-ai/*` client package the shell serves from its module table;
 *  2. wrap that body in the loader call, with `module`/`exports` created inside
 *     the factory exactly as the official artifacts do;
 *  3. write `lib/client.js` and delete the intermediate body.
 *
 * Deliberately not attempted here: CSS compilation and chunk splitting. A
 * browser half that needs a stylesheet injects it from a module of its own (see
 * `src/client/styles.ts` in the live-tasks package), which keeps one toolchain
 * for the whole repository.
 *
 * Exit codes: 0 built (or nothing to build), 1 a bundle failed.
 */
import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const packagesDir = join(root, 'packages')
const BODY_SUFFIX = '.client-body.js'

/** Host-provided modules the loader resolves through the factory's `require`. */
const EXTERNAL = ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client', /^@deepseek-ai\//]

function clientEntries() {
  return readdirSync(packagesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .map((name) => {
      const dir = join(packagesDir, name)
      const tsx = join(dir, 'src/client/index.tsx')
      const ts = join(dir, 'src/client/index.ts')
      if (existsSync(tsx)) return { name, dir, entry: tsx }
      if (existsSync(ts)) return { name, dir, entry: ts }
      return undefined
    })
    .filter((value) => value !== undefined)
    .toSorted((a, b) => a.name.localeCompare(b.name))
}

const targets = clientEntries()
if (targets.length === 0) {
  console.log('build-client: no browser half in this workspace')
  process.exit(0)
}

let failed = 0
for (const target of targets) {
  const manifest = JSON.parse(readFileSync(join(target.dir, 'package.json'), 'utf8'))
  const outDir = join(target.dir, 'lib')
  const body = join(outDir, `index${BODY_SUFFIX}`)
  const artifact = join(outDir, 'client.js')
  try {
    rmSync(body, { force: true })
    const { build } = await import('tsdown')
    await build({
      // Inline config only: the root tsdown.config.ts describes the host halves.
      config: false,
      entry: [target.entry],
      outDir,
      format: 'cjs',
      platform: 'browser',
      dts: false,
      clean: false,
      sourcemap: false,
      outExtensions: () => ({ js: BODY_SUFFIX }),
      deps: { neverBundle: EXTERNAL },
    })

    if (!existsSync(body)) throw new Error(`tsdown produced no ${body}`)
    const moduleBody = readFileSync(body, 'utf8').replace(/\/\/#\s*sourceMappingURL=.*$/m, '')
    writeFileSync(artifact, [
      '// Generated by scripts/build-client.mjs — do not edit by hand.',
      'window.__ModuleLoader__.load({',
      `\tid: ${JSON.stringify(manifest.name)},`,
      '\tfactory: (require) => {',
      '\t\tvar module = { exports: {} };',
      '\t\tvar exports = module.exports;',
      '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
      moduleBody.trimEnd(),
      '\t\treturn module.exports;',
      '\t}',
      '});',
      '',
    ].join('\n'))
    rmSync(body, { force: true })
    const bytes = readFileSync(artifact).length
    console.log(`build-client: ✓ ${manifest.name} → lib/client.js (${bytes} B)`)
  } catch (error) {
    failed += 1
    console.error(`build-client: ✗ ${target.name}`)
    const output = `${error.stdout ?? ''}${error.stderr ?? ''}${error.message ?? ''}`.trim()
    if (output) console.error(output.split('\n').slice(-8).join('\n'))
  }
}

if (failed > 0) {
  console.error(`build-client: ${failed} of ${targets.length} browser half(s) failed`)
  process.exit(1)
}
console.log(`build-client: OK — ${targets.length} browser half(s)`)
