/** Class names this view applies. */
export declare const styles: {
    readonly view: 'lt-view';
    readonly head: 'lt-head';
    readonly elapsed: 'lt-elapsed';
    readonly section: 'lt-section';
    readonly sectionHead: 'lt-sectionHead';
    readonly sectionTitle: 'lt-sectionTitle';
    readonly stats: 'lt-stats';
    readonly stat: 'lt-stat';
    readonly statLabel: 'lt-statLabel';
    readonly statValue: 'lt-statValue';
    readonly statValueFailed: 'lt-statValueFailed';
    readonly list: 'lt-list';
    readonly call: 'lt-call';
    readonly callDetail: 'lt-callDetail';
    readonly callTook: 'lt-callTook';
    readonly filters: 'lt-filters';
    readonly filter: 'lt-filter';
    readonly filterActive: 'lt-filterActive';
    readonly table: 'lt-table';
    readonly th: 'lt-th';
    readonly rowFailed: 'lt-rowFailed';
    readonly tdTime: 'lt-tdTime';
    readonly tdTool: 'lt-tdTool';
    readonly tdWhat: 'lt-tdWhat';
    readonly tdTook: 'lt-tdTook';
    readonly tdResult: 'lt-tdResult';
    readonly resultLine: 'lt-resultLine';
    readonly badgeOk: 'lt-badgeOk';
    readonly badgeFailed: 'lt-badgeFailed';
    readonly health: 'lt-health';
    readonly healthStale: 'lt-healthStale';
    readonly toolName: 'lt-toolName';
    readonly none: 'lt-none';
    readonly empty: 'lt-empty';
};
